<a href="https://colab.research.google.com/github/luluremwu/wikidataupload/blob/main/wikidataupload.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ==========================================
# Cell 1：Install & Import libraries(環境與套件設定)
# Import Python 套件、設定 Wikidata API endpoint、基本環境
# ==========================================
import pandas as pd
import requests
import json
import time
import re
import logging
from pathlib import Path

# Google Colab 專用
from google.colab import files

# 顯示完整欄位內容
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

# 建立 log
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)

print("Libraries imported successfully.")

Libraries imported successfully.

In [ ]:
# ==========================================
# Cell 2：Wikidata API & OAuth 2.0 設定(OAuth 驗證)
# 使用目前已經測試成功的 OAuth 2.0 驗證 Wikidata 帳號與 API 連線
# ==========================================

API_URL = "https://www.wikidata.org/w/api.php"

ACCESS_TOKEN = "your token"

HEADERS = {
    "User-Agent": (
        "Your oAuthname/1.0 "
        "(https://www.wikidata.org/wiki/User:Your username)"
    ),
    "Authorization": f"Bearer {ACCESS_TOKEN}"
}

session = requests.Session()
session.headers.update(HEADERS)

params = {
    "action": "query",
    "meta": "userinfo",
    "uiprop": "rights",
    "format": "json"
}

response = session.get(API_URL, params=params)
data = response.json()

print("Wikidata API configuration loaded.")
print("HTTP status:", response.status_code)
print("Username:", data["query"]["userinfo"]["name"])
print("User ID:", data["query"]["userinfo"]["id"])
print("OAuth authentication: SUCCESS")

Wikidata API configuration loaded.
HTTP status: 200
Username: Kenwu99034
User ID: 8352669
OAuth authentication: SUCCESS

In [ ]:
# ==========================================
# Cell 3：匯入資料
# 經 OpenRefine 處理後的 Excel／CSV，讀成 DataFram
# ==========================================

from google.colab import files
import pandas as pd
import os

# 上傳檔案
uploaded = files.upload()

# 取得上傳的檔名
file_path = list(uploaded.keys())[0]

print(f"\n已選擇檔案：{file_path}")

# 判斷副檔名
ext = os.path.splitext(file_path)[1].lower()

if ext == ".csv":
    df = pd.read_csv(file_path)

elif ext in [".xlsx", ".xls"]:
    df = pd.read_excel(file_path)

else:
    raise ValueError(f"不支援的檔案格式：{ext}")

print("\n" + "=" * 60)
print("資料讀取成功")
print("=" * 60)

print(f"資料筆數：{len(df)}")
print(f"欄位數量：{len(df.columns)}")

print("\n欄位名稱：")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

print("\n前 5 筆資料：")
display(df.head())

Saving 陶瓷器.xlsx to 陶瓷器.xlsx

已選擇檔案：陶瓷器.xlsx

============================================================
資料讀取成功
============================================================
資料筆數：4
欄位數量：18

欄位名稱：
1. 排序
2. 原始網頁標題
3. reconcile_title
4. 搜尋狀態
5. 文物統一編號
6. 品名
7. 英文品名
8. 朝代
9. 分類
10. 作者
11. 高度
12. 寬度
13. 徑
14. 質地
15. 主題
16. 描述
17. 圖片
18. url

前 5 筆資料：

,排序,原始網頁標題,reconcile_title,搜尋狀態,文物統一編號,品名,英文品名,朝代,分類,作者,高度,寬度,徑,質地,主題,描述,圖片,url
0,20,宋 十一至十三世紀 建窯 黑釉兔毫盞,建窯 黑釉兔毫盞,找不到,故瓷008624N000000000,建窯 黑釉兔毫盞,"Bowl with ""hare' s fur"" striations on a black ground, Jian ware",宋,陶瓷器,none,6.5,none,11.5,陶瓷,none,弇口碗，口沿外緣向內束收，深腹、小圈足。釉施不及底，旦露深褐色粗厚的器胎。足外壁無釉，足內則淺凹，並深刻一「律」字楷書。釉色鳥黑濃稠且流動性大，外壁垂淌至近足處，內底積厚釉，口緣則薄釉而形成特徵的「褐口邊」。,建窯_黑釉兔毫盞.jpg,https://digitalarchive.npm.gov.tw/Collection/Detail/53?dep=U
1,42,明 永樂 青花一把蓮紋盤,永樂 青花一把蓮紋盤,找不到,故瓷002306N000000000,青花一把蓮紋盤,Dish with lotus flowers decoration in underglaze blue,明,陶瓷器,none,5.8,none,21.5,陶瓷,none,盤子弧壁，矮圈足。器底露胎，全器以青花為飾。口沿下飾卷草紋，內壁有蓮花、石榴、菊花等各式花朵共十三朵。外壁口沿下繪回紋，壁面畫纏枝花卉十四朵，近圈足處有卷草紋一周。,青花一把蓮紋盤.jpg,https://digitalarchive.npm.gov.tw/Collection/Detail/38753?dep=U
2,45,清 康熙 豇豆紅釉太白尊,康熙 豇豆紅釉太白尊,成功,中瓷000047N000000000,豇豆紅釉太白尊,Flat bulbous vase with red glaze,清,陶瓷器,none,8.5,none,3.2,陶瓷,none,小口微外侈，短頸溜肩，廣腹，形似半圓球，平底凹足。器身施銅紅釉，因受窯爐溫度影響，呈色有深淺之別，類似豇(音同姜)豆色澤，故有豇豆紅釉之說。器腹淺劃三組暗花團螭紋，口沿及器內施白釉，外底有「大清康熙年製」楷體款識。,豇豆紅釉太白尊.jpg,https://digitalarchive.npm.gov.tw/Collection/Detail/1793?dep=U
3,50,清 乾隆 粉彩蟠桃天球瓶,乾隆 粉彩蟠桃天球瓶,成功,中瓷000034N000000000,粉彩蟠桃天球瓶,Celestial globe vase with polychrome decoration of peaches in fencai painted enamels,清,陶瓷器,none,50.5,none,38.3,陶瓷,none,天球瓶，瓷胎，直口，長頸，寬圓肩，大圓腹，矮圈足。全器為粉彩描繪桃樹、桃花及桃實。構圖生動如畫，色彩粉嫩，表面作顆粒狀浮起，足緣露胎，呈白色。底部為白地藍書「大清乾隆年製」三行篆書款。,粉彩蟠桃天球瓶.jpg,https://digitalarchive.npm.gov.tw/Collection/Detail/18995?dep=U

In [ ]:
# ============================================================
# Cell 4：整理 Wikidata 上傳資料(資料前處理)
# 整理欄位、空值、基本格式，建立後續程式可以統一處理的資料結構；像 P195 = Q540668 這類固定值也在這階段處理
# ============================================================

import pandas as pd

# ------------------------------------------------------------
# 1. 固定 Wikidata 資料
# ------------------------------------------------------------

NPM_QID = "Q540668"

# ------------------------------------------------------------
# 2. 不需要上傳 Wikidata 的欄位
# ------------------------------------------------------------

IGNORE_COLUMNS = [
    "排序",
    "原始網頁標題",
    "reconcile_title",
    "搜尋狀態"
]

# ============================================================
# 判斷欄位是否真的有值
# ============================================================

def has_value(value):

    # Python None
    if value is None:
        return False

    # pandas NaN / NA
    if pd.isna(value):
        return False

    # 轉成文字並清除前後空白
    text = str(value).strip()

    # 空字串
    if text == "":
        return False

    # 常見「文字型空值」
    if text.lower() in {
        "none",
        "nan",
        "null",
        "n/a",
        "na"
    }:
        return False

    return True


# ------------------------------------------------------------
# 4. 建立工作用 DataFrame
# ------------------------------------------------------------

wikidata_df = df.copy()

# 移除不需要的欄位
wikidata_df = wikidata_df.drop(
    columns=[col for col in IGNORE_COLUMNS if col in wikidata_df.columns]
)


# ------------------------------------------------------------
# 5. 加入固定 collection
# ------------------------------------------------------------

wikidata_df["P195"] = NPM_QID


# ------------------------------------------------------------
# 6. 顯示目前欄位
# ------------------------------------------------------------

print("=" * 60)
print("Cell 4：資料整理完成")
print("=" * 60)

print(f"資料筆數：{len(wikidata_df)}")

print("\n目前保留欄位：")

for i, col in enumerate(wikidata_df.columns, 1):
    print(f"{i}. {col}")


print("\n前 5 筆整理後資料：")

display(wikidata_df.head())

============================================================
Cell 4：資料整理完成
============================================================
資料筆數：4

目前保留欄位：
1. 文物統一編號
2. 品名
3. 英文品名
4. 朝代
5. 分類
6. 作者
7. 高度
8. 寬度
9. 徑
10. 質地
11. 主題
12. 描述
13. 圖片
14. url
15. P195

前 5 筆整理後資料：

,文物統一編號,品名,英文品名,朝代,分類,作者,高度,寬度,徑,質地,主題,描述,圖片,url,P195
0,故瓷008624N000000000,建窯 黑釉兔毫盞,"Bowl with ""hare' s fur"" striations on a black ground, Jian ware",宋,陶瓷器,none,6.5,none,11.5,陶瓷,none,弇口碗，口沿外緣向內束收，深腹、小圈足。釉施不及底，旦露深褐色粗厚的器胎。足外壁無釉，足內則淺凹，並深刻一「律」字楷書。釉色鳥黑濃稠且流動性大，外壁垂淌至近足處，內底積厚釉，口緣則薄釉而形成特徵的「褐口邊」。,建窯_黑釉兔毫盞.jpg,https://digitalarchive.npm.gov.tw/Collection/Detail/53?dep=U,Q540668
1,故瓷002306N000000000,青花一把蓮紋盤,Dish with lotus flowers decoration in underglaze blue,明,陶瓷器,none,5.8,none,21.5,陶瓷,none,盤子弧壁，矮圈足。器底露胎，全器以青花為飾。口沿下飾卷草紋，內壁有蓮花、石榴、菊花等各式花朵共十三朵。外壁口沿下繪回紋，壁面畫纏枝花卉十四朵，近圈足處有卷草紋一周。,青花一把蓮紋盤.jpg,https://digitalarchive.npm.gov.tw/Collection/Detail/38753?dep=U,Q540668
2,中瓷000047N000000000,豇豆紅釉太白尊,Flat bulbous vase with red glaze,清,陶瓷器,none,8.5,none,3.2,陶瓷,none,小口微外侈，短頸溜肩，廣腹，形似半圓球，平底凹足。器身施銅紅釉，因受窯爐溫度影響，呈色有深淺之別，類似豇(音同姜)豆色澤，故有豇豆紅釉之說。器腹淺劃三組暗花團螭紋，口沿及器內施白釉，外底有「大清康熙年製」楷體款識。,豇豆紅釉太白尊.jpg,https://digitalarchive.npm.gov.tw/Collection/Detail/1793?dep=U,Q540668
3,中瓷000034N000000000,粉彩蟠桃天球瓶,Celestial globe vase with polychrome decoration of peaches in fencai painted enamels,清,陶瓷器,none,50.5,none,38.3,陶瓷,none,天球瓶，瓷胎，直口，長頸，寬圓肩，大圓腹，矮圈足。全器為粉彩描繪桃樹、桃花及桃實。構圖生動如畫，色彩粉嫩，表面作顆粒狀浮起，足緣露胎，呈白色。底部為白地藍書「大清乾隆年製」三行篆書款。,粉彩蟠桃天球瓶.jpg,https://digitalarchive.npm.gov.tw/Collection/Detail/18995?dep=U,Q540668

In [ ]:
# ============================================================
# Cell 5：資料轉換 + 通用 QID Resolver(資料轉換＋QID Resolver)
# 把「朝代、作者、材質、分類、主題」等文字轉成 Wikidata 所需 QID；先查 local mapping，再透過 wbsearchentities 找候選
# ============================================================

import pandas as pd
import requests
from pprint import pprint


# ============================================================
# 1. Mapping 設定
# ============================================================

CATEGORY_MAP = {
    "瓷器": "Q45621",
    "畫作": "Q3305213",
    "書法": "Q12681",
    "法帖": "Q10563458",
    "法帖": "Q12681",
    "玉器": "Q60733799",
    "文具": "Q875696",
    "銅器": "Q34095"
}


DYNASTY_MAP = {
    "宋朝": "Q319460",
    "清朝": "Q8733",
    "明朝": "Q9903",
    "唐朝": "Q9683",
    "元朝": "Q7313",
    "周朝": "Q35216",

    "宋": "Q319460",
    "清": "Q8733",
    "明": "Q9903",
    "唐": "Q9683",
    "周": "Q35216",
    "元": "Q7313"
}


MATERIAL_MAP = {
    "瓷器": "Q130693",
    "瓷": "Q130693",
    "紙": "Q11472",
    "絲綢": "Q37681",
    "絹": "Q37681",
    "青銅": "Q34095",
    "玉": "Q175089",
    "紫檀木": "Q122421"
}


SUBJECT_MAP = {
    "山水畫": "Q516583",
    "山水": "Q516583",
    "人物": "Q1792372",
    "后妃": "Q16138124",
    "宮殿": "Q16560"
}


# 已人工確認過的作者可以逐步放進這裡
AUTHOR_MAP = {
}


# ============================================================
# 2. 通用 QID Resolver
# ============================================================

def resolve_qid(
    value,
    local_map=None,
    search_wikidata=False,
    language="zh"
):

    value = str(value).strip()


    # --------------------------------------------------------
    # 已經是 QID
    # --------------------------------------------------------

    if value.startswith("Q") and value[1:].isdigit():

        return {
            "status": "MATCH",
            "qid": value,
            "value": value,
            "source": "input",
            "candidates": []
        }


    # --------------------------------------------------------
    # Local Mapping
    # --------------------------------------------------------

    if local_map is not None:

        qid = local_map.get(value)

        if qid:

            return {
                "status": "MATCH",
                "qid": qid,
                "value": value,
                "source": "local_map",
                "candidates": []
            }


    # --------------------------------------------------------
    # 不使用 Wikidata Search
    # --------------------------------------------------------

    if not search_wikidata:

        return {
            "status": "NOT_FOUND",
            "qid": None,
            "value": value,
            "source": None,
            "candidates": []
        }


    # --------------------------------------------------------
    # Wikidata Search API
    # --------------------------------------------------------

    api_url = "https://www.wikidata.org/w/api.php"

    params = {
        "action": "wbsearchentities",
        "search": value,
        "language": language,
        "uselang": "zh-tw",
        "type": "item",
        "limit": 5,
        "format": "json"
    }


    # ★ 這就是剛才測試成功的關鍵
    headers = {
        "User-Agent": (
            "NPM-Wikidata-Upload-Tool/0.1 "
            "(Wikidata user: Kenwu99034)"
        )
    }


    try:

        response = requests.get(
            api_url,
            params=params,
            headers=headers,
            timeout=15
        )

        response.raise_for_status()

        results = response.json().get(
            "search",
            []
        )


    except Exception as e:

        return {
            "status": "ERROR",
            "qid": None,
            "value": value,
            "source": "wikidata",
            "candidates": [],
            "error": str(e)
        }


    # --------------------------------------------------------
    # 搜尋不到
    # --------------------------------------------------------

    if len(results) == 0:

        return {
            "status": "NOT_FOUND",
            "qid": None,
            "value": value,
            "source": "wikidata",
            "candidates": []
        }


    # --------------------------------------------------------
    # 搜尋得到候選
    # 目前不直接採用第一筆
    # --------------------------------------------------------

    candidates = []

    for item in results:

        candidates.append({
            "qid": item.get("id"),
            "label": item.get("label"),
            "description": item.get("description")
        })


    return {
        "status": "AMBIGUOUS",
        "qid": None,
        "value": value,
        "source": "wikidata",
        "candidates": candidates
    }


# ============================================================
# 3. 其他轉換 Function
# ============================================================

def clean_commons_filename(value):

    value = str(value).strip()

    if value.lower().startswith("file:"):
        value = value[5:].strip()

    return value


def to_number(value):

    try:
        return float(value)

    except (ValueError, TypeError):
        return None


# ============================================================
# 4. 建立 Wikidata Records
# ============================================================

wikidata_records = []


for index, row in wikidata_df.iterrows():

    record = {
        "row_number": index + 1,
        "labels": {},
        "descriptions": {},
        "statements": {},
        "unresolved": {}
    }


    # ========================================================
    # Label
    # ========================================================

    if has_value(row.get("品名")):

        record["labels"]["zh-tw"] = str(
            row["品名"]
        ).strip()


    if has_value(row.get("英文品名")):

        record["labels"]["en"] = str(
            row["英文品名"]
        ).strip()


    # ========================================================
    # Description
    # ========================================================

    if has_value(row.get("描述")):

        record["descriptions"]["zh-tw"] = str(
            row["描述"]
        ).strip()


    # ========================================================
    # P195 - 國立故宮博物院
    # ========================================================

    record["statements"]["P195"] = "Q540668"


    # ========================================================
    # P217 - 文物統一編號
    # ========================================================

    if has_value(row.get("文物統一編號")):

        record["statements"]["P217"] = str(
            row["文物統一編號"]
        ).strip()


    # ========================================================
    # 朝代 → P2348
    # ========================================================

    if has_value(row.get("朝代")):

        result = resolve_qid(
            row["朝代"],
            DYNASTY_MAP,
            search_wikidata=True
        )

        if result["status"] == "MATCH":

            record["statements"]["P2348"] = result["qid"]

        else:

            record["unresolved"]["朝代"] = result


    # ========================================================
    # 作者 → P170
    # ========================================================

    if has_value(row.get("作者")):

        result = resolve_qid(
            row["作者"],
            AUTHOR_MAP,
            search_wikidata=True
        )

        if result["status"] == "MATCH":

            record["statements"]["P170"] = result["qid"]

        else:

            record["unresolved"]["作者"] = result


    # ========================================================
    # 質地 → P186
    # ========================================================

    if has_value(row.get("質地")):

        result = resolve_qid(
            row["質地"],
            MATERIAL_MAP,
            search_wikidata=True
        )

        if result["status"] == "MATCH":

            record["statements"]["P186"] = result["qid"]

        else:

            record["unresolved"]["質地"] = result


    # ========================================================
    # 分類 → P31
    # instance of
    # ========================================================

    if has_value(row.get("分類")):

        result = resolve_qid(
            row["分類"],
            CATEGORY_MAP,
            search_wikidata=True
        )

        if result["status"] == "MATCH":

            record["statements"]["P31"] = result["qid"]

        else:

            record["unresolved"]["分類"] = result


    # ========================================================
    # P2048 - 高度
    # ========================================================

    if has_value(row.get("高度")):

        height = to_number(
            row["高度"]
        )

        if height is not None:

            record["statements"]["P2048"] = {
                "amount": height,
                "unit": "cm"
            }

        else:

            record["unresolved"]["高度"] = {
                "status": "INVALID_NUMBER",
                "value": row["高度"]
            }


    # ========================================================
    # P2049 - 寬度
    # ========================================================

    if has_value(row.get("寬度")):

        width = to_number(
            row["寬度"]
        )

        if width is not None:

            record["statements"]["P2049"] = {
                "amount": width,
                "unit": "cm"
            }

        else:

            record["unresolved"]["寬度"] = {
                "status": "INVALID_NUMBER",
                "value": row["寬度"]
            }

    # ========================================================
    # P2386
    # 徑 / diameter
    # ========================================================

    if has_value(row.get("徑")):

        diameter = to_number(
            row["徑"]
        )

        if diameter is not None:

            record["statements"]["P2386"] = {
                "amount": diameter,
                "unit": "cm"
            }

        else:

            record["unresolved"]["徑"] = {
                "status": "INVALID_NUMBER",
                "value": row["徑"]
            }

    # ========================================================
    # P18 - Wikimedia Commons
    # ========================================================

    if has_value(row.get("圖片")):

        record["statements"]["P18"] = (
            clean_commons_filename(
                row["圖片"]
            )
        )


    # ========================================================
    # URL
    # ========================================================

    if has_value(row.get("url")):

        record["source_url"] = str(
            row["url"]
        ).strip()


    wikidata_records.append(record)

    # ========================================================
    # 主題 → P921
    # ========================================================

    if has_value(row.get("主題")):

        result = resolve_qid(
            row["主題"],
            SUBJECT_MAP,
            search_wikidata=True
        )

        if result["status"] == "MATCH":

            record["statements"]["P921"] = result["qid"]

        else:

            record["unresolved"]["主題"] = result

# ============================================================
# 5. 顯示結果
# ============================================================

print("=" * 70)
print("Cell 5：Wikidata 資料轉換完成")
print("=" * 70)

print(
    f"總資料筆數：{len(wikidata_records)}"
)


print("\n第一筆資料：")
print("-" * 70)

pprint(
    wikidata_records[0],
    sort_dicts=False
)


# ============================================================
# 6. 顯示 unresolved
# ============================================================

print("\n" + "=" * 70)
print("需要確認的資料")
print("=" * 70)


unresolved_count = 0


for record in wikidata_records:

    if record["unresolved"]:

        unresolved_count += 1

        print(
            f"\n第 {record['row_number']} 筆"
        )

        for field, result in record["unresolved"].items():

            print(
                f"\n  {field}:"
            )

            pprint(
                result,
                indent=4,
                sort_dicts=False
            )


print("\n" + "=" * 70)

print(
    f"共有 {unresolved_count} 筆資料需要確認"
)

======================================================================
Cell 5：Wikidata 資料轉換完成
======================================================================
總資料筆數：4

第一筆資料：
----------------------------------------------------------------------
{'row_number': 1,
 'labels': {'zh-tw': '建窯 黑釉兔毫盞',
            'en': 'Bowl with "hare\' s fur" striations on a black ground, Jian '
                  'ware'},
 'descriptions': {'zh-tw': '弇口碗，口沿外緣向內束收，深腹、小圈足。釉施不及底，旦露深褐色粗厚的器胎。足外壁無釉，足內則淺凹，並深刻一「律」字楷書。釉色鳥黑濃稠且流動性大，外壁垂淌至近足處，內底積厚釉，口緣則薄釉而形成特徵的「褐口邊」。'},
 'statements': {'P195': 'Q540668',
                'P217': '故瓷008624N000000000',
                'P2348': 'Q319460',
                'P2048': {'amount': 6.5, 'unit': 'cm'},
                'P2386': {'amount': 11.5, 'unit': 'cm'},
                'P18': '建窯_黑釉兔毫盞.jpg'},
 'unresolved': {'質地': {'status': 'AMBIGUOUS',
                       'qid': None,
                       'value': '陶瓷',
                       'source': 'wikidata',
                       'candidates': [{'qid': 'Q45621',
                                       'label': '陶瓷',
                                       'description': 'inorganic, nonmetallic '
                                                      'solid prepared by the '
                                                      'action of heat'},
                                      {'qid': 'Q5065024',
                                       'label': '陶瓷',
                                       'description': '西班牙電影'},
                                      {'qid': 'Q13464614',
                                       'label': '陶瓷藝術',
                                       'description': 'art objects made from '
                                                      'clay and other raw '
                                                      'materials by the '
                                                      'process of pottery'},
                                      {'qid': 'Q17379525',
                                       'label': '陶瓷器',
                                       'description': '物體的分類，不同於製陶工藝'},
                                      {'qid': 'Q1936199',
                                       'label': '陶瓷工程',
                                       'description': 'branch of engineering '
                                                      'concerned with the '
                                                      'development, '
                                                      'production, and '
                                                      'application of ceramic '
                                                      'and ceramic products'}]},
                '分類': {'status': 'AMBIGUOUS',
                       'qid': None,
                       'value': '陶瓷器',
                       'source': 'wikidata',
                       'candidates': [{'qid': 'Q45621',
                                       'label': '陶瓷',
                                       'description': 'inorganic, nonmetallic '
                                                      'solid prepared by the '
                                                      'action of heat'},
                                      {'qid': 'Q17379525',
                                       'label': '陶瓷器',
                                       'description': '物體的分類，不同於製陶工藝'},
                                      {'qid': 'Q113218301',
                                       'label': '陶瓷器蓋子',
                                       'description': '藝術家雜誌收錄文章'},
                                      {'qid': 'Q121351215',
                                       'label': '陶瓷器造型的模擬轉化',
                                       'description': 'scholarly article in '
                                                      'Journal of Nanjing Arts '
                                                      'Institute (Fine Arts & '
                                                      'Design), no. 1, 2014'},
                                      {'qid': 'Q121403760',
                                       'label': '陶瓷器的裝飾',
                                       'description': 'scholarly article in '
                                                      'Art & Design, no. 1, '
                                                      '1992'}]}},
 'source_url': 'https://digitalarchive.npm.gov.tw/Collection/Detail/53?dep=U'}

======================================================================
需要確認的資料
======================================================================

第 1 筆

  質地:
{   'status': 'AMBIGUOUS',
    'qid': None,
    'value': '陶瓷',
    'source': 'wikidata',
    'candidates': [   {   'qid': 'Q45621',
                          'label': '陶瓷',
                          'description': 'inorganic, nonmetallic solid '
                                         'prepared by the action of heat'},
                      {   'qid': 'Q5065024',
                          'label': '陶瓷',
                          'description': '西班牙電影'},
                      {   'qid': 'Q13464614',
                          'label': '陶瓷藝術',
                          'description': 'art objects made from clay and other '
                                         'raw materials by the process of '
                                         'pottery'},
                      {   'qid': 'Q17379525',
                          'label': '陶瓷器',
                          'description': '物體的分類，不同於製陶工藝'},
                      {   'qid': 'Q1936199',
                          'label': '陶瓷工程',
                          'description': 'branch of engineering concerned with '
                                         'the development, production, and '
                                         'application of ceramic and ceramic '
                                         'products'}]}

  分類:
{   'status': 'AMBIGUOUS',
    'qid': None,
    'value': '陶瓷器',
    'source': 'wikidata',
    'candidates': [   {   'qid': 'Q45621',
                          'label': '陶瓷',
                          'description': 'inorganic, nonmetallic solid '
                                         'prepared by the action of heat'},
                      {   'qid': 'Q17379525',
                          'label': '陶瓷器',
                          'description': '物體的分類，不同於製陶工藝'},
                      {   'qid': 'Q113218301',
                          'label': '陶瓷器蓋子',
                          'description': '藝術家雜誌收錄文章'},
                      {   'qid': 'Q121351215',
                          'label': '陶瓷器造型的模擬轉化',
                          'description': 'scholarly article in Journal of '
                                         'Nanjing Arts Institute (Fine Arts & '
                                         'Design), no. 1, 2014'},
                      {   'qid': 'Q121403760',
                          'label': '陶瓷器的裝飾',
                          'description': 'scholarly article in Art & Design, '
                                         'no. 1, 1992'}]}

第 2 筆

  質地:
{   'status': 'AMBIGUOUS',
    'qid': None,
    'value': '陶瓷',
    'source': 'wikidata',
    'candidates': [   {   'qid': 'Q45621',
                          'label': '陶瓷',
                          'description': 'inorganic, nonmetallic solid '
                                         'prepared by the action of heat'},
                      {   'qid': 'Q5065024',
                          'label': '陶瓷',
                          'description': '西班牙電影'},
                      {   'qid': 'Q13464614',
                          'label': '陶瓷藝術',
                          'description': 'art objects made from clay and other '
                                         'raw materials by the process of '
                                         'pottery'},
                      {   'qid': 'Q17379525',
                          'label': '陶瓷器',
                          'description': '物體的分類，不同於製陶工藝'},
                      {   'qid': 'Q1936199',
                          'label': '陶瓷工程',
                          'description': 'branch of engineering concerned with '
                                         'the development, production, and '
                                         'application of ceramic and ceramic '
                                         'products'}]}

  分類:
{   'status': 'AMBIGUOUS',
    'qid': None,
    'value': '陶瓷器',
    'source': 'wikidata',
    'candidates': [   {   'qid': 'Q45621',
                          'label': '陶瓷',
                          'description': 'inorganic, nonmetallic solid '
                                         'prepared by the action of heat'},
                      {   'qid': 'Q17379525',
                          'label': '陶瓷器',
                          'description': '物體的分類，不同於製陶工藝'},
                      {   'qid': 'Q113218301',
                          'label': '陶瓷器蓋子',
                          'description': '藝術家雜誌收錄文章'},
                      {   'qid': 'Q121351215',
                          'label': '陶瓷器造型的模擬轉化',
                          'description': 'scholarly article in Journal of '
                                         'Nanjing Arts Institute (Fine Arts & '
                                         'Design), no. 1, 2014'},
                      {   'qid': 'Q121403760',
                          'label': '陶瓷器的裝飾',
                          'description': 'scholarly article in Art & Design, '
                                         'no. 1, 1992'}]}

第 3 筆

  質地:
{   'status': 'AMBIGUOUS',
    'qid': None,
    'value': '陶瓷',
    'source': 'wikidata',
    'candidates': [   {   'qid': 'Q45621',
                          'label': '陶瓷',
                          'description': 'inorganic, nonmetallic solid '
                                         'prepared by the action of heat'},
                      {   'qid': 'Q5065024',
                          'label': '陶瓷',
                          'description': '西班牙電影'},
                      {   'qid': 'Q13464614',
                          'label': '陶瓷藝術',
                          'description': 'art objects made from clay and other '
                                         'raw materials by the process of '
                                         'pottery'},
                      {   'qid': 'Q17379525',
                          'label': '陶瓷器',
                          'description': '物體的分類，不同於製陶工藝'},
                      {   'qid': 'Q1936199',
                          'label': '陶瓷工程',
                          'description': 'branch of engineering concerned with '
                                         'the development, production, and '
                                         'application of ceramic and ceramic '
                                         'products'}]}

  分類:
{   'status': 'AMBIGUOUS',
    'qid': None,
    'value': '陶瓷器',
    'source': 'wikidata',
    'candidates': [   {   'qid': 'Q45621',
                          'label': '陶瓷',
                          'description': 'inorganic, nonmetallic solid '
                                         'prepared by the action of heat'},
                      {   'qid': 'Q17379525',
                          'label': '陶瓷器',
                          'description': '物體的分類，不同於製陶工藝'},
                      {   'qid': 'Q113218301',
                          'label': '陶瓷器蓋子',
                          'description': '藝術家雜誌收錄文章'},
                      {   'qid': 'Q121351215',
                          'label': '陶瓷器造型的模擬轉化',
                          'description': 'scholarly article in Journal of '
                                         'Nanjing Arts Institute (Fine Arts & '
                                         'Design), no. 1, 2014'},
                      {   'qid': 'Q121403760',
                          'label': '陶瓷器的裝飾',
                          'description': 'scholarly article in Art & Design, '
                                         'no. 1, 1992'}]}

第 4 筆

  質地:
{   'status': 'AMBIGUOUS',
    'qid': None,
    'value': '陶瓷',
    'source': 'wikidata',
    'candidates': [   {   'qid': 'Q45621',
                          'label': '陶瓷',
                          'description': 'inorganic, nonmetallic solid '
                                         'prepared by the action of heat'},
                      {   'qid': 'Q5065024',
                          'label': '陶瓷',
                          'description': '西班牙電影'},
                      {   'qid': 'Q13464614',
                          'label': '陶瓷藝術',
                          'description': 'art objects made from clay and other '
                                         'raw materials by the process of '
                                         'pottery'},
                      {   'qid': 'Q17379525',
                          'label': '陶瓷器',
                          'description': '物體的分類，不同於製陶工藝'},
                      {   'qid': 'Q1936199',
                          'label': '陶瓷工程',
                          'description': 'branch of engineering concerned with '
                                         'the development, production, and '
                                         'application of ceramic and ceramic '
                                         'products'}]}

  分類:
{   'status': 'AMBIGUOUS',
    'qid': None,
    'value': '陶瓷器',
    'source': 'wikidata',
    'candidates': [   {   'qid': 'Q45621',
                          'label': '陶瓷',
                          'description': 'inorganic, nonmetallic solid '
                                         'prepared by the action of heat'},
                      {   'qid': 'Q17379525',
                          'label': '陶瓷器',
                          'description': '物體的分類，不同於製陶工藝'},
                      {   'qid': 'Q113218301',
                          'label': '陶瓷器蓋子',
                          'description': '藝術家雜誌收錄文章'},
                      {   'qid': 'Q121351215',
                          'label': '陶瓷器造型的模擬轉化',
                          'description': 'scholarly article in Journal of '
                                         'Nanjing Arts Institute (Fine Arts & '
                                         'Design), no. 1, 2014'},
                      {   'qid': 'Q121403760',
                          'label': '陶瓷器的裝飾',
                          'description': 'scholarly article in Art & Design, '
                                         'no. 1, 1992'}]}

======================================================================
共有 4 筆資料需要確認

In [ ]:
# ============================================================
# Cell 6：候選 QID 自動判斷(QID 候選判斷)
# 不修改 Cell 5 的 wikidata_records
# 把 Cell 5 找到的結果分成 MATCH、AMBIGUOUS、NOT_FOUND、ERROR 等狀態，不會看到第一個搜尋結果就直接當答案
# ============================================================

import copy
from pprint import pprint


# ============================================================
# 1. 複製 Cell 5 結果
# ============================================================

resolved_records = copy.deepcopy(wikidata_records)


# ============================================================
# 2. 欄位判斷規則
# ============================================================

FIELD_KEYWORDS = {
    "主題": [
        "主題",
        "題材",
        "subject",
        "theme",
        "topic"
    ],

    "質地": [
        "材料",
        "材質",
        "material",
        "substance"
    ],

    "作者": [
        "畫家",
        "書法家",
        "藝術家",
        "雕刻家",
        "painter",
        "artist",
        "calligrapher",
        "sculptor",
        "person"
    ],

    "分類": [
        "藝術",
        "作品",
        "文物",
        "器物",
        "art",
        "artwork",
        "object"
    ],

    "朝代": [
        "朝代",
        "王朝",
        "dynasty"
    ]
}


# ============================================================
# 3. 單一候選評分
# ============================================================

def score_candidate(
    original_value,
    candidate,
    field_name
):

    score = 0

    original_value = str(
        original_value
    ).strip().lower()

    label = str(
        candidate.get("label") or ""
    ).strip().lower()

    description = str(
        candidate.get("description") or ""
    ).strip().lower()

    reasons = []


    # Label 完全一致
    if label == original_value:

        score += 70

        reasons.append(
            "Label 完全一致"
        )


    # Label 部分一致
    elif (
        original_value in label
        or label in original_value
    ):

        score += 30

        reasons.append(
            "Label 部分一致"
        )


    # Description 關鍵字
    keywords = FIELD_KEYWORDS.get(
        field_name,
        []
    )

    for keyword in keywords:

        if keyword.lower() in description:

            score += 10

            reasons.append(
                f"Description 包含：{keyword}"
            )

            break


    return {
        "qid": candidate.get("qid"),
        "label": candidate.get("label"),
        "description": candidate.get("description"),
        "score": score,
        "reasons": reasons
    }


# ============================================================
# 4. 判斷 unresolved
# ============================================================

def evaluate_unresolved(
    field_name,
    result
):

    if result.get("status") != "AMBIGUOUS":

        return {
            "status": result.get("status"),
            "qid": None,
            "confidence": "NONE",
            "original": result.get("value"),
            "ranked_candidates": []
        }


    original_value = result.get(
        "value"
    )

    candidates = result.get(
        "candidates",
        []
    )


    scored = []

    for candidate in candidates:

        scored.append(
            score_candidate(
                original_value,
                candidate,
                field_name
            )
        )


    scored.sort(
        key=lambda x: x["score"],
        reverse=True
    )


    if len(scored) == 0:

        return {
            "status": "NOT_FOUND",
            "qid": None,
            "confidence": "NONE",
            "original": original_value,
            "ranked_candidates": []
        }


    best = scored[0]

    second_score = (
        scored[1]["score"]
        if len(scored) > 1
        else 0
    )


    # 自動接受規則
    if (
        best["score"] >= 80
        and
        best["score"] - second_score >= 20
    ):

        return {
            "status": "AUTO_MATCH",
            "qid": best["qid"],
            "confidence": "HIGH",
            "original": original_value,
            "best_candidate": best,
            "ranked_candidates": scored
        }


    # 需要人工確認
    return {
        "status": "REVIEW",
        "qid": None,
        "confidence": "LOW",
        "original": original_value,
        "best_candidate": best,
        "ranked_candidates": scored
    }


# ============================================================
# 5. Property 對應
# ============================================================

PROPERTY_MAP = {
    "分類": "P31",
    "質地": "P186",
    "作者": "P170",
    "主題": "P921",
    "朝代": "P2348"
}


# ============================================================
# 6. 處理所有 resolved_records
# ============================================================

review_records = []


for record in resolved_records:

    resolved_after_review = {}

    remaining_unresolved = {}


    for field_name, result in record["unresolved"].items():

        if not isinstance(result, dict):

            remaining_unresolved[field_name] = result
            continue


        if result.get("status") != "AMBIGUOUS":

            remaining_unresolved[field_name] = result
            continue


        evaluation = evaluate_unresolved(
            field_name,
            result
        )


        # 自動確認成功
        if evaluation["status"] == "AUTO_MATCH":

            resolved_after_review[
                field_name
            ] = evaluation["qid"]


        # 仍需確認
        else:

            remaining_unresolved[
                field_name
            ] = evaluation


    # ========================================================
    # 寫回 resolved_records
    # ========================================================

    for field_name, qid in resolved_after_review.items():

        property_id = PROPERTY_MAP.get(
            field_name
        )


        if property_id:

            record["statements"][
                property_id
            ] = qid
        else:

            record[
                f"resolved_{field_name}"
            ] = qid


    # 更新 unresolved
    record["unresolved"] = (
        remaining_unresolved
    )


    # 建立人工確認清單
    if remaining_unresolved:

        review_records.append({

            "row_number":
                record["row_number"],

            "label":
                record["labels"].get(
                    "zh-tw",
                    ""
                ),

            "unresolved":
                remaining_unresolved
        })


# ============================================================
# 7. 顯示摘要
# ============================================================

print("=" * 70)
print("Cell 6：QID 候選判斷完成")
print("=" * 70)

print(
    f"總資料筆數：{len(resolved_records)}"
)

print(
    f"仍需人工確認：{len(review_records)} 筆"
)


# ============================================================
# 8. 顯示第一筆結果
# ============================================================

print("\n第一筆處理後結果：")
print("-" * 70)

print("Statements：")

pprint(
    resolved_records[0]["statements"],
    sort_dicts=False
)


if "resolved_category" in resolved_records[0]:

    print(
        "\n分類：",
        resolved_records[0]["resolved_category"]
    )


# ============================================================
# 9. 顯示人工確認摘要
# ============================================================

if review_records:

    print("\n需要人工確認：")
    print("-" * 70)

    for item in review_records:

        print(
            f"\n第 {item['row_number']} 筆 "
            f"{item['label']}"
        )

        for field_name, result in item[
            "unresolved"
        ].items():

            print(
                f"  - {field_name}: "
                f"{result.get('original', '')}"
            )

            best = result.get(
                "best_candidate"
            )

            if best:

                print(
                    f"    最佳候選："
                    f"{best['qid']} | "
                    f"{best['label']} | "
                    f"score={best['score']}"
                )

======================================================================
Cell 6：QID 候選判斷完成
======================================================================
總資料筆數：4
仍需人工確認：4 筆

第一筆處理後結果：
----------------------------------------------------------------------
Statements：
{'P195': 'Q540668',
 'P217': '故瓷008624N000000000',
 'P2348': 'Q319460',
 'P2048': {'amount': 6.5, 'unit': 'cm'},
 'P2386': {'amount': 11.5, 'unit': 'cm'},
 'P18': '建窯_黑釉兔毫盞.jpg'}

需要人工確認：
----------------------------------------------------------------------

第 1 筆 建窯 黑釉兔毫盞
  - 質地: 陶瓷
    最佳候選：Q45621 | 陶瓷 | score=70
  - 分類: 陶瓷器
    最佳候選：Q17379525 | 陶瓷器 | score=70

第 2 筆 青花一把蓮紋盤
  - 質地: 陶瓷
    最佳候選：Q45621 | 陶瓷 | score=70
  - 分類: 陶瓷器
    最佳候選：Q17379525 | 陶瓷器 | score=70

第 3 筆 豇豆紅釉太白尊
  - 質地: 陶瓷
    最佳候選：Q45621 | 陶瓷 | score=70
  - 分類: 陶瓷器
    最佳候選：Q17379525 | 陶瓷器 | score=70

第 4 筆 粉彩蟠桃天球瓶
  - 質地: 陶瓷
    最佳候選：Q45621 | 陶瓷 | score=70
  - 分類: 陶瓷器
    最佳候選：Q17379525 | 陶瓷器 | score=70

In [ ]:
# ============================================================
# Cell 7：互動式人工確認介面(人工確認候選)
# 對 AMBIGUOUS 等無法安全自動判斷的欄位進行人工確認，決定真正要使用的 QID
# ============================================================

import copy
import re
import ipywidgets as widgets
from IPython.display import display, clear_output


# ============================================================
# 1. 從 Cell 6 複製結果
# ============================================================

final_records = copy.deepcopy(resolved_records)


# ============================================================
# 2. Property 對應
# ============================================================

PROPERTY_MAP = {
    "分類": "P31",
    "質地": "P186",
    "作者": "P170",
    "朝代": "P2348"
}


# ============================================================
# 3. QID 格式檢查
# ============================================================

def is_valid_qid(value):

    if value is None:
        return False

    value = str(value).strip()

    return bool(
        re.fullmatch(r"Q\d+", value)
    )


# ============================================================
# 4. 收集需要人工確認的項目
# ============================================================

review_queue = []


for record_index, record in enumerate(final_records):

    for field_name, result in record.get(
        "unresolved",
        {}
    ).items():

        if not isinstance(result, dict):
            continue

        # 只有 REVIEW / AMBIGUOUS 類型進人工介面
        status = result.get("status")

        if status not in [
            "REVIEW",
            "AMBIGUOUS"
        ]:
            continue


        original_value = (
            result.get("original")
            or result.get("value")
        )


        candidates = (
            result.get("ranked_candidates")
            or result.get("candidates")
            or []
        )


        review_queue.append({
            "record_index": record_index,
            "row_number": record.get(
                "row_number"
            ),
            "label": record.get(
                "labels",
                {}
            ).get(
                "zh-tw",
                ""
            ),
            "field_name": field_name,
            "original_value": original_value,
            "candidates": candidates
        })


# ============================================================
# 5. 如果沒有需要人工確認的資料
# ============================================================

if len(review_queue) == 0:

    print("=" * 70)
    print("Cell 7：沒有需要人工確認的 QID")
    print("=" * 70)

else:

    # ========================================================
    # 6. 狀態
    # ========================================================

    current_index = 0


    # ========================================================
    # 7. UI 元件
    # ========================================================

    title_output = widgets.Output()

    candidate_dropdown = widgets.Dropdown(
        options=[],
        description="候選：",
        layout=widgets.Layout(
            width="95%"
        )
    )

    manual_qid_input = widgets.Text(
        value="",
        placeholder="例如 Q82001",
        description="手動 QID：",
        layout=widgets.Layout(
            width="60%"
        )
    )

    confirm_button = widgets.Button(
        description="確認此 QID",
        button_style="success"
    )

    manual_button = widgets.Button(
        description="使用手動 QID",
        button_style="info"
    )

    skip_button = widgets.Button(
        description="跳過此欄位",
        button_style="warning"
    )

    status_output = widgets.Output()


    # ========================================================
    # 8. 寫入 QID 的 Function
    # ========================================================

    def apply_qid(
        record,
        field_name,
        qid
    ):

        property_id = PROPERTY_MAP.get(
            field_name
        )


        if property_id:

            record["statements"][
                property_id
            ] = qid
        else:

            record[
                f"resolved_{field_name}"
            ] = qid


        # 從 unresolved 移除
        record["unresolved"].pop(
            field_name,
            None
        )


    # ========================================================
    # 9. 顯示目前項目
    # ========================================================

    def show_current():

        nonlocal_current = None

        with title_output:

            clear_output()

            if current_index >= len(review_queue):

                print("=" * 70)
                print("Cell 7：人工確認完成")
                print("=" * 70)
                return


            item = review_queue[
                current_index
            ]

            print(
                f"進度："
                f"{current_index + 1}"
                f" / "
                f"{len(review_queue)}"
            )

            print()

            print(
                f"第 {item['row_number']} 筆"
            )

            print(
                f"文物：{item['label']}"
            )

            print(
                f"欄位：{item['field_name']}"
            )

            print(
                f"原始值："
                f"{item['original_value']}"
            )


        if current_index >= len(review_queue):
            candidate_dropdown.options = []
            return


        item = review_queue[
            current_index
        ]

        options = []


        for candidate in item[
            "candidates"
        ]:

            qid = candidate.get(
                "qid"
            )

            label = candidate.get(
                "label"
            )

            description = candidate.get(
                "description"
            )

            score = candidate.get(
                "score"
            )


            text = (
                f"{qid} | "
                f"{label}"
            )


            if description:

                text += (
                    f" | {description}"
                )


            if score is not None:

                text += (
                    f" | score={score}"
                )


            options.append(
                (
                    text,
                    qid
                )
            )


        candidate_dropdown.options = (
            options
        )


        if len(options) > 0:

            candidate_dropdown.value = (
                options[0][1]
            )


        manual_qid_input.value = ""


    # ========================================================
    # 10. 下一筆
    # ========================================================

    def go_next():

        global current_index

        current_index += 1

        show_current()


    # ========================================================
    # 11. 按下「確認候選」
    # ========================================================

    def confirm_candidate(
        button
    ):

        global current_index

        if current_index >= len(
            review_queue
        ):
            return


        qid = (
            candidate_dropdown.value
        )


        with status_output:

            clear_output()

            if not is_valid_qid(qid):

                print(
                    "❌ 候選 QID 格式不正確"
                )

                return


            item = review_queue[
                current_index
            ]

            record = final_records[
                item["record_index"]
            ]


            apply_qid(
                record,
                item["field_name"],
                qid
            )


            print(
                f"✅ 已套用："
                f"{item['field_name']} "
                f"→ {qid}"
            )


        current_index += 1

        show_current()


    # ========================================================
    # 12. 按下「手動 QID」
    # ========================================================

    def confirm_manual(
        button
    ):

        global current_index

        if current_index >= len(
            review_queue
        ):
            return


        qid = (
            manual_qid_input.value
            .strip()
        )


        with status_output:

            clear_output()

            if not is_valid_qid(qid):

                print(
                    "❌ 請輸入有效 QID，"
                    "例如 Q82001"
                )

                return


            item = review_queue[
                current_index
            ]

            record = final_records[
                item["record_index"]
            ]


            apply_qid(
                record,
                item["field_name"],
                qid
            )


            print(
                f"✅ 已手動套用："
                f"{item['field_name']} "
                f"→ {qid}"
            )


        current_index += 1

        show_current()


    # ========================================================
    # 13. 跳過
    # ========================================================

    def skip_current(
        button
    ):

        global current_index

        if current_index >= len(
            review_queue
        ):
            return


        item = review_queue[
            current_index
        ]


        with status_output:

            clear_output()

            print(
                f"⏭️ 已跳過："
                f"{item['field_name']} "
                f"= "
                f"{item['original_value']}"
            )


        current_index += 1

        show_current()


    # ========================================================
    # 14. 綁定按鈕
    # ========================================================

    confirm_button.on_click(
        confirm_candidate
    )

    manual_button.on_click(
        confirm_manual
    )

    skip_button.on_click(
        skip_current
    )


    # ========================================================
    # 15. 顯示 UI
    # ========================================================

    display(
        title_output
    )

    display(
        candidate_dropdown
    )

    display(
        widgets.HBox([
            confirm_button,
            skip_button
        ])
    )

    display(
        widgets.HBox([
            manual_qid_input,
            manual_button
        ])
    )

    display(
        status_output
    )


    show_current()

Output()

Dropdown(description='候選：', layout=Layout(width='95%'), options=(), value=None)

HBox(children=(Button(button_style='success', description='確認此 QID', style=ButtonStyle()), Button(button_style…

HBox(children=(Text(value='', description='手動 QID：', layout=Layout(width='60%'), placeholder='例如 Q82001'), But…

Output()

In [ ]:
# ============================================================
# Cell 8：Wikidata 上傳前 Validation(Validation)
# 正式上傳前總檢查：必填欄位、QID、數值、格式、未解決欄位等；有問題的資料先擋下來
# ============================================================

import re
from pprint import pprint


# ============================================================
# 1. 基本檢查 Function
# ============================================================

def valid_qid(value):
    """
    檢查 QID 格式
    """
    if not isinstance(value, str):
        return False

    return bool(
        re.fullmatch(r"Q\d+", value.strip())
    )


def valid_quantity(value):
    """
    檢查目前中介格式的 quantity
    """

    if not isinstance(value, dict):
        return False

    if "amount" not in value:
        return False

    if "unit" not in value:
        return False

    try:
        float(value["amount"])
    except (ValueError, TypeError):
        return False

    return True


# ============================================================
# 2. 定義各 Property 的資料類型
# ============================================================

ITEM_PROPERTIES = {
    "P31",    # instance of
    "P195",   # collection
    "P170",   # creator
    "P186",   # material
    "P2348",   # time period
    "P921"
}


QUANTITY_PROPERTIES = {
    "P2048",  # 高度
    "P2049",  # 寬度
    "P2386"   # 徑 / diameter
}


STRING_PROPERTIES = {
    "P217"    # inventory number
}


MEDIA_PROPERTIES = {
    "P18"
}


# ============================================================
# 3. 開始驗證
# ============================================================

validation_results = []

ready_records = []
blocked_records = []


for record_index, record in enumerate(final_records):

    errors = []
    warnings = []

    row_number = record.get(
        "row_number",
        record_index + 1
    )

    label = (
        record.get("labels", {})
        .get("zh-tw")
    )

    statements = record.get(
        "statements",
        {}
    )


    # ========================================================
    # A. Label
    # ========================================================

    if not has_value(label):

        errors.append(
            "缺少 zh-tw Label（品名）"
        )


    # ========================================================
    # B. P31 - 分類 / instance of
    # 必要欄位
    # ========================================================

    if "P31" not in statements:

        errors.append(
            "缺少 P31（分類 / instance of）"
        )

    elif not valid_qid(statements["P31"]):

        errors.append(
            f"P31 QID 格式錯誤：{statements['P31']}"
        )


    # ========================================================
    # C. P195
    # ========================================================

    if "P195" not in statements:

        errors.append(
            "缺少 P195（collection）"
        )

    elif statements["P195"] != "Q540668":

        warnings.append(
            f"P195 不是預期的國立故宮博物院 Q540668："
            f"{statements['P195']}"
        )


    # ========================================================
    # D. P217
    # ========================================================

    if "P217" not in statements:

        errors.append(
            "缺少 P217（文物統一編號）"
        )

    elif not has_value(
        statements["P217"]
    ):

        errors.append(
            "P217 為空值"
        )


    # ========================================================
    # E. unresolved
    # ========================================================

    unresolved = record.get(
        "unresolved",
        {}
    )

    if unresolved:

        warnings.append(
            "仍存在未解析欄位："
            + ", ".join(
                unresolved.keys()
            )
        )


    # ========================================================
    # F. Statement 格式檢查
    # ========================================================

    for property_id, value in statements.items():

        # ----------------------------------------------------
        # Item
        # ----------------------------------------------------

        if property_id in ITEM_PROPERTIES:

            if not valid_qid(value):

                errors.append(
                    f"{property_id} QID 格式錯誤：{value}"
                )


        # ----------------------------------------------------
        # Quantity
        # ----------------------------------------------------

        elif property_id in QUANTITY_PROPERTIES:

            if not valid_quantity(value):

                errors.append(
                    f"{property_id} quantity 格式錯誤：{value}"
                )

            else:

                if value["unit"] != "cm":

                    warnings.append(
                        f"{property_id} 單位不是 cm："
                        f"{value['unit']}"
                    )


        # ----------------------------------------------------
        # String
        # ----------------------------------------------------

        elif property_id in STRING_PROPERTIES:

            if not has_value(value):

                errors.append(
                    f"{property_id} 為空值"
                )


        # ----------------------------------------------------
        # Commons Media
        # ----------------------------------------------------

        elif property_id in MEDIA_PROPERTIES:

            if not has_value(value):

                errors.append(
                    "P18 圖片名稱為空"
                )

            elif str(value).lower().startswith(
                "file:"
            ):

                warnings.append(
                    "P18 仍包含 File: 前綴"
                )
    # ========================================================
    # G. Source URL
    # ========================================================

    source_url = record.get(
        "source_url"
    )

    if not has_value(source_url):

        warnings.append(
            "缺少來源 URL"
        )


    # ========================================================
    # H. 最終狀態
    # ========================================================

    if errors:

        status = "BLOCKED"

    elif warnings:

        status = "WARNING"

    else:

        status = "READY"


    result = {
        "record_index": record_index,
        "row_number": row_number,
        "label": label,
        "status": status,
        "errors": errors,
        "warnings": warnings
    }


    validation_results.append(
        result
    )


    if status == "BLOCKED":

        blocked_records.append(
            result
        )

    else:

        ready_records.append(
            record
        )


# ============================================================
# 4. 統計
# ============================================================

ready_count = sum(
    1
    for x in validation_results
    if x["status"] == "READY"
)

warning_count = sum(
    1
    for x in validation_results
    if x["status"] == "WARNING"
)

blocked_count = sum(
    1
    for x in validation_results
    if x["status"] == "BLOCKED"
)


print("=" * 70)
print("Cell 8：Wikidata 上傳前檢查")
print("=" * 70)

print(
    f"總資料：{len(validation_results)}"
)

print(
    f"✅ READY：{ready_count}"
)

print(
    f"⚠️ WARNING：{warning_count}"
)

print(
    f"❌ BLOCKED：{blocked_count}"
)


# ============================================================
# 5. 顯示問題
# ============================================================

for result in validation_results:

    if result["status"] == "READY":
        continue


    print("\n" + "-" * 70)

    print(
        f"第 {result['row_number']} 筆"
    )

    print(
        f"文物：{result['label']}"
    )

    print(
        f"狀態：{result['status']}"
    )


    if result["errors"]:

        print("\n錯誤：")

        for error in result["errors"]:

            print(
                f"  ❌ {error}"
            )


    if result["warnings"]:

        print("\n警告：")

        for warning in result["warnings"]:

            print(
                f"  ⚠️ {warning}"
            )


# ============================================================
# 6. 是否允許進入下一階段
# ============================================================

print("\n" + "=" * 70)

if blocked_count > 0:

    print(
        "❌ 目前存在 BLOCKED 資料，"
        "尚不建議進入 Wikidata 上傳階段。"
    )

else:

    print(
        "✅ 沒有 BLOCKED 資料，"
        "可以進入下一階段。"
    )

======================================================================
Cell 8：Wikidata 上傳前檢查
======================================================================
總資料：1
✅ READY：1
⚠️ WARNING：0
❌ BLOCKED：0

======================================================================
✅ 沒有 BLOCKED 資料，可以進入下一階段。

In [ ]:
# ============================================================
# Cell 9：Wikibase JSON Builder(建立 Wikidata Payload)
# ready_records → api_payloads
# 把確認完成的資料轉成 Wikibase API 可以接受的 Entity JSON，包括 labels、descriptions、statements、references、qualifiers
# 注意：
# 這個 Cell 只產生 JSON
# 不會上傳 Wikidata
# ============================================================

import copy

# ============================================================
# 1. Wikidata 設定
# ============================================================

WIKIDATA_ENTITY_BASE = "http://www.wikidata.org/entity/"

CM_UNIT_QID = "Q174728"

CM_UNIT_URI = (
    WIKIDATA_ENTITY_BASE
    + CM_UNIT_QID
)


# ============================================================
# 2. Property 資料型態設定
# ============================================================

ITEM_PROPERTIES = {
    "P31",    # instance of / 分類
    "P195",   # collection
    "P170",   # creator
    "P186",   # material
    "P2348",  # time period
    "P921"    # main subject
}


STRING_PROPERTIES = {
    "P217"    # inventory number
}


QUANTITY_PROPERTIES = {
    "P2048",  # height
    "P2049",  # width
    "P2386"   # diameter
}


MEDIA_PROPERTIES = {
    "P18"
}


# ============================================================
# 3. 哪些 statement 要加故宮來源 Reference
# ============================================================

REFERENCE_PROPERTIES = {
    "P31",
    "P170",
    "P186",
    "P2348",
    "P921",
    "P2048",
    "P2049",
    "P2386",
    "P217"
}


# ============================================================
# 4. QID → Wikibase entity datavalue
# ============================================================

def build_item_datavalue(qid):

    qid = str(qid).strip()

    numeric_id = int(
        qid[1:]
    )

    return {
        "value": {
            "entity-type": "item",
            "numeric-id": numeric_id,
            "id": qid
        },
        "type": "wikibase-entityid"
    }


# ============================================================
# 5. String datavalue
# ============================================================

def build_string_datavalue(value):

    return {
        "value": str(value),
        "type": "string"
    }


# ============================================================
# 6. Commons Media datavalue
# ============================================================

def build_media_datavalue(value):

    return {
        "value": str(value),
        "type": "string"
    }


# ============================================================
# 7. URL datavalue
# ============================================================

def build_url_datavalue(value):

    return {
        "value": str(value),
        "type": "string"
    }


# ============================================================
# 8. Quantity datavalue
# ============================================================

def build_quantity_datavalue(
    amount,
    unit_uri=CM_UNIT_URI
):

    amount = float(amount)

    # Wikibase quantity amount 建議使用有正負號的字串
    if amount >= 0:
        amount_string = f"+{amount}"
    else:
        amount_string = str(amount)


    return {
        "value": {
            "amount": amount_string,
            "unit": unit_uri
        },
        "type": "quantity"
    }

# ============================================================
# Qualifier Builder
# 用於建立 Item 型態的 qualifier
# ============================================================

def build_item_qualifier(
    property_id,
    qid
):

    return {
        "snaktype": "value",
        "property": property_id,
        "datatype": "wikibase-item",
        "datavalue": build_item_datavalue(
            qid
        )
    }

# ============================================================
# 9. Reference Builder
# P854 = reference URL
# ============================================================

def build_reference(source_url):

    return {
        "snaks": {

            "P854": [
                {
                    "snaktype": "value",
                    "property": "P854",
                    "datatype": "url",
                    "datavalue":
                        build_url_datavalue(
                            source_url
                        )
                }
            ]

        },

        "snaks-order": [
            "P854"
        ]
    }


# ============================================================
# 10. Statement Builder
# ============================================================

def build_statement(
    property_id,
    value,
    source_url=None
):

    # --------------------------------------------------------
    # Item
    # --------------------------------------------------------

    if property_id in ITEM_PROPERTIES:

        datatype = (
            "wikibase-item"
        )

        datavalue = (
            build_item_datavalue(
                value
            )
        )


    # --------------------------------------------------------
    # String
    # --------------------------------------------------------

    elif property_id in STRING_PROPERTIES:

        datatype = "string"

        datavalue = (
            build_string_datavalue(
                value
            )
        )


    # --------------------------------------------------------
    # Quantity
    # --------------------------------------------------------

    elif property_id in QUANTITY_PROPERTIES:

        datatype = "quantity"

        datavalue = (
            build_quantity_datavalue(
                value["amount"]
            )
        )


    # --------------------------------------------------------
    # Commons Media
    # --------------------------------------------------------

    elif property_id in MEDIA_PROPERTIES:

        datatype = (
            "commonsMedia"
        )

        datavalue = (
            build_media_datavalue(
                value
            )
        )


    else:

        raise ValueError(
            f"尚未定義 Property datatype："
            f"{property_id}"
        )


    # --------------------------------------------------------
    # Claim 基本結構
    # --------------------------------------------------------

    statement = {

        "mainsnak": {

            "snaktype": "value",

            "property": property_id,

            "datatype": datatype,

            "datavalue": datavalue
        },

        "type": "statement",

        "rank": "normal"
    }

    # --------------------------------------------------------
    # P217 - 收藏編號
    #
    # Wikidata 要求 inventory number
    # 使用 P195（collection）作為 qualifier
    #
    # P217 = 收藏編號
    #   └─ P195 = 國立故宮博物院
    # --------------------------------------------------------

    if property_id == "P217":

        statement["qualifiers"] = {

            "P195": [

                build_item_qualifier(
                    "P195",
                    "Q540668"
                )

            ]

        }

        statement["qualifiers-order"] = [
            "P195"
        ]

    # --------------------------------------------------------
    # Reference
    # --------------------------------------------------------

    if (
        source_url
        and
        property_id
        in REFERENCE_PROPERTIES
    ):

        statement[
            "references"
        ] = [
            build_reference(
                source_url
            )
        ]


    return statement


# ============================================================
# 11. 建立單一 Wikibase Item Payload
# ============================================================

def build_item_payload(record):

    payload = {

        "labels": {},

        "descriptions": {},

        "claims": {}
    }


    # ========================================================
    # Labels
    # ========================================================

    for language, value in (
        record
        .get("labels", {})
        .items()
    ):

        payload[
            "labels"
        ][language] = {

            "language":
                language,

            "value":
                value
        }


    # ========================================================
    # Descriptions
    # ========================================================

    for language, value in (
        record
        .get(
            "descriptions",
            {}
        )
        .items()
    ):

        payload[
            "descriptions"
        ][language] = {

            "language":
                language,

            "value":
                value
        }


    # ========================================================
    # Source URL
    # ========================================================

    source_url = record.get(
        "source_url"
    )


    # ========================================================
    # Statements
    # ========================================================

    for property_id, value in (
        record
        .get(
            "statements",
            {}
        )
        .items()
    ):

        statement = build_statement(
            property_id,
            value,
            source_url
        )


        if property_id not in (
            payload["claims"]
        ):

            payload[
                "claims"
            ][property_id] = []


        payload[
            "claims"
        ][property_id].append(
            statement
        )


    # ========================================================
    # P973 - described at URL
    # ========================================================

    if source_url:

        p973_statement = {

            "mainsnak": {

                "snaktype":
                    "value",

                "property":
                    "P973",

                "datatype":
                    "url",

                "datavalue":
                    build_url_datavalue(
                        source_url
                    )
            },

            "type":
                "statement",

            "rank":
                "normal"
        }


        payload[
            "claims"
        ]["P973"] = [
            p973_statement
        ]


    return payload


# ============================================================
# 12. 建立全部 Payload
# ============================================================

api_payloads = []


for record in ready_records:

    item_payload = (
        build_item_payload(
            record
        )
    )


    api_payloads.append({

        "row_number":
            record.get(
                "row_number"
            ),

        "label":
            record
            .get(
                "labels",
                {}
            )
            .get(
                "zh-tw",
                ""
            ),

        "data":
            item_payload
    })


# ============================================================
# 13. 輸出摘要
# ============================================================

print("=" * 70)
print("Cell 9：Wikibase JSON Builder 完成")
print("=" * 70)

print(
    f"準備 Payload 數量："
    f"{len(api_payloads)}"
)

print()

print(
    "✅ 已建立 api_payloads"
)

print(
    "⚠️ 尚未傳送任何資料到 Wikidata"
)

======================================================================
Cell 9：Wikibase JSON Builder 完成
======================================================================
準備 Payload 數量：1

✅ 已建立 api_payloads
⚠️ 尚未傳送任何資料到 Wikidata

In [ ]:
# ============================================================
# Cell 10：Wikidata 上傳前 Preview (Upload Preview)
# 正式寫入 Wikidata 前，把準備送出的 Item 顯示出來，讓你最後人工確認
# api_payloads → 人類可讀預覽
# 注意：
# 這個 Cell 不會上傳任何資料
# ============================================================

# ============================================================
# 1. Property 顯示名稱
# ============================================================

PROPERTY_LABELS = {
    "P31": "分類 / instance of",
    "P195": "藏於 / collection",
    "P217": "文物統一編號",
    "P2348": "朝代 / time period",
    "P170": "作者 / creator",
    "P186": "質地 / material",
    "P921": "主題 / main subject",
    "P2048": "高度 / height",
    "P2049": "寬度 / width",
    "P2386": "徑 / diameter",
    "P18": "圖片 / image",
    "P973": "描述網址 / described at URL"
}


# ============================================================
# 2. 讀取 Statement Value
# ============================================================

def preview_statement_value(
    property_id,
    statement
):

    mainsnak = statement.get(
        "mainsnak",
        {}
    )

    datavalue = mainsnak.get(
        "datavalue",
        {}
    )

    value = datavalue.get(
        "value"
    )


    # --------------------------------------------------------
    # Wikidata Item
    # --------------------------------------------------------

    if property_id in {
        "P31",
        "P195",
        "P170",
        "P186",
        "P2348",
        "P921"
    }:

        if isinstance(value, dict):

            return value.get(
                "id",
                "?"
            )

        return str(value)


    # --------------------------------------------------------
    # Quantity
    # --------------------------------------------------------

    if property_id in {
        "P2048",
        "P2049",
        "P2386"
    }:

        if isinstance(value, dict):

            amount = value.get(
                "amount",
                "?"
            )

            # 去掉 + 號
            amount = str(
                amount
            ).lstrip("+")

            unit = value.get(
                "unit",
                ""
            )

            # 目前只使用 cm
            if unit.endswith(
                "Q174728"
            ):

                unit_name = "cm"

            else:

                unit_name = unit


            return (
                f"{amount} "
                f"{unit_name}"
            )


    # --------------------------------------------------------
    # String / Media / URL
    # --------------------------------------------------------

    return str(value)

# ============================================================
# 讀取 Qualifier
# ============================================================

def preview_qualifiers(statement):

    qualifiers = statement.get(
        "qualifiers",
        {}
    )

    result = []


    for property_id, snaks in qualifiers.items():

        for snak in snaks:

            datavalue = snak.get(
                "datavalue",
                {}
            )

            value = datavalue.get(
                "value"
            )


            # ------------------------------------------------
            # Item 類型，例如 P195 → Q540668
            # ------------------------------------------------

            if isinstance(value, dict):

                display_value = value.get(
                    "id",
                    "?"
                )

            else:

                display_value = value


            result.append({
                "property": property_id,
                "value": display_value
            })


    return result

# ============================================================
# 3. 讀取 Reference
# ============================================================

def preview_references(
    statement
):

    references = statement.get(
        "references",
        []
    )

    urls = []


    for reference in references:

        snaks = reference.get(
            "snaks",
            {}
        )

        p854_list = snaks.get(
            "P854",
            []
        )


        for snak in p854_list:

            datavalue = snak.get(
                "datavalue",
                {}
            )

            url = datavalue.get(
                "value"
            )

            if url:

                urls.append(
                    url
                )


    return urls


# ============================================================
# 4. 顯示 Preview
# ============================================================

print("=" * 75)
print("Cell 10：Wikidata 上傳前 Preview")
print("=" * 75)

print(
    f"準備上傳：{len(api_payloads)} 筆"
)

print(
    "⚠️ 目前尚未送出任何資料"
)


# ============================================================
# 5. 一筆一筆顯示
# ============================================================

for payload_index, item in enumerate(
    api_payloads,
    1
):

    data = item["data"]


    print(
        "\n"
        + "=" * 75
    )

    print(
        f"[ {payload_index} / "
        f"{len(api_payloads)} ]"
    )

    print(
        f"原資料列："
        f"{item.get('row_number')}"
    )


    # ========================================================
    # Labels
    # ========================================================

    print("\n【Labels】")

    labels = data.get(
        "labels",
        {}
    )


    if labels:

        for language, label_data in (
            labels.items()
        ):

            print(
                f"  {language}: "
                f"{label_data.get('value')}"
            )

    else:

        print(
            "  （無）"
        )


    # ========================================================
    # Descriptions
    # ========================================================

    print("\n【Descriptions】")

    descriptions = data.get(
        "descriptions",
        {}
    )


    if descriptions:

        for language, desc_data in (
            descriptions.items()
        ):

            print(
                f"  {language}: "
                f"{desc_data.get('value')}"
            )

    else:

        print(
            "  （無）"
        )


    # ========================================================
    # Statements
    # ========================================================

    print("\n【Statements】")

    claims = data.get(
        "claims",
        {}
    )


    if not claims:

        print(
            "  （無）"
        )


    for property_id, statement_list in (
        claims.items()
    ):

        property_name = (
            PROPERTY_LABELS.get(
                property_id,
                property_id
            )
        )


        for statement in statement_list:

            display_value = (
                preview_statement_value(
                    property_id,
                    statement
                )
            )


            print(
                f"  {property_id} "
                f"({property_name})"
            )

            print(
                f"      → "
                f"{display_value}"
            )

            # ================================================
            # Qualifier
            # ================================================

            qualifiers = preview_qualifiers(
                statement
            )


            for qualifier in qualifiers:

                qualifier_property = (
                    qualifier["property"]
                )

                qualifier_value = (
                    qualifier["value"]
                )


                qualifier_name = (
                    PROPERTY_LABELS.get(
                        qualifier_property,
                        qualifier_property
                    )
                )


                print(
                    f"      └─ Qualifier "
                    f"{qualifier_property} "
                    f"({qualifier_name})"
                )

                print(
                    f"           → "
                    f"{qualifier_value}"
                )

    # ========================================================
    # Reference 摘要
    # ========================================================

    reference_urls = set()

    for statement_list in claims.values():

        for statement in statement_list:

            for url in preview_references(statement):

                reference_urls.add(url)


    if reference_urls:

        print("\n【References】")

        for url in reference_urls:

            print(
                f"  P854 → {url}"
            )

    print(
        "\n"
        + "-" * 75
    )

    print(
        "⚠️ Preview only — "
        "尚未上傳 Wikidata"
    )


print(
    "\n"
    + "=" * 75
)

print(
    "Cell 10 Preview 完成"
)

print(
    "請確認資料內容後，"
    "再進入實際上傳階段。"
)

===========================================================================
Cell 10：Wikidata 上傳前 Preview
===========================================================================
準備上傳：1 筆
⚠️ 目前尚未送出任何資料

===========================================================================
[ 1 / 1 ]
原資料列：1

【Labels】
  zh-tw: 乃孫作祖己鼎
  en: Ding cauldron with inscription "Naisun zuo zuji"

【Descriptions】
  zh-tw: 此器為深腹，折沿，立耳，柱足鼎。器腹微微下垂具有西周早期的風格。頸飾六組高浮雕獸面紋，獸面中央有一道扉稜，雲雷紋襯地。柱足上有高浮雕扉稜獸面紋及三道弦紋。器壁厚，紋飾精細。器腹底有一補鑄痕。

【Statements】
  P195 (藏於 / collection)
      → Q540668
  P217 (文物統一編號)
      → 故銅002343N000000000
      └─ Qualifier P195 (藏於 / collection)
           → Q540668
  P2348 (朝代 / time period)
      → Q35216
  P186 (質地 / material)
      → Q34095
  P31 (分類 / instance of)
      → Q34095
  P2048 (高度 / height)
      → 81.8 cm
  P18 (圖片 / image)
      → 乃孫作祖己鼎.jpg
  P973 (描述網址 / described at URL)
      → https://digitalarchive.npm.gov.tw/Collection/Detail/53476?dep=U

【References】
  P854 → https://digitalarchive.npm.gov.tw/Collection/Detail/53476?dep=U

---------------------------------------------------------------------------
⚠️ Preview only — 尚未上傳 Wikidata

===========================================================================
Cell 10 Preview 完成
請確認資料內容後，再進入實際上傳階段。

In [ ]:
# ============================================================
# Cell 11.5：Wikidata 登入 / 權限 / Global Block 檢查
#
# 不會建立或修改 Wikidata Item
# ============================================================

import requests

API_URL = "https://www.wikidata.org/w/api.php"

print("=" * 70)
print("Cell 11.5：Wikidata 上傳環境檢查")
print("=" * 70)


wikidata_login_ok = False
wikidata_block_ok = False
wikidata_upload_ok = False


try:

    # ========================================================
    # 1. 登入與權限檢查
    # ========================================================

    response = session.get(
        API_URL,
        params={
            "action": "query",
            "meta": "userinfo",
            "uiprop": "rights",
            "assert": "user",
            "format": "json"
        },
        timeout=30
    )

    print(
        f"HTTP Status：{response.status_code}"
    )

    response.raise_for_status()

    result = response.json()

    userinfo = (
        result
        .get("query", {})
        .get("userinfo", {})
    )

    username = userinfo.get(
        "name"
    )

    user_id = userinfo.get(
        "id"
    )

    rights = userinfo.get(
        "rights",
        []
    )


    if not username:

        print()
        print("❌ Wikidata 登入狀態異常")

    else:

        wikidata_login_ok = True

        print()
        print("✅ Wikidata 登入狀態正常")

        print()
        print(
            f"使用者：{username}"
        )

        print(
            f"User ID：{user_id}"
        )


        # ====================================================
        # 2. 必要權限
        # ====================================================

        print()
        print("必要權限：")

        required_rights = [
            "read",
            "edit",
            "createpage"
        ]

        missing_rights = []


        for right in required_rights:

            if right in rights:

                print(
                    f"✅ {right}"
                )

            else:

                print(
                    f"❌ {right}"
                )

                missing_rights.append(
                    right
                )


        if missing_rights:

            wikidata_login_ok = False


    # ========================================================
    # 3. 查目前 Colab 對外 IP
    # ========================================================

    print()
    print("-" * 70)

    print(
        "正在檢查目前 Colab 對外 IP..."
    )


    ip_response = requests.get(
        "https://api.ipify.org",
        params={
            "format": "json"
        },
        timeout=15
    )

    ip_response.raise_for_status()

    current_ip = (
        ip_response
        .json()
        .get("ip")
    )


    print(
        f"目前 IP：{current_ip}"
    )


    # ========================================================
    # 4. Wikimedia Global Block 查詢
    # ========================================================

    block_response = session.get(
        API_URL,
        params={
            "action": "query",
            "list": "globalblocks",
            "bgip": current_ip,
            "bgprop":
                "id|target|by|timestamp|expiry|reason|range",
            "format": "json"
        },
        timeout=30
    )

    block_response.raise_for_status()

    block_data = (
        block_response
        .json()
    )

    global_blocks = (
        block_data
        .get("query", {})
        .get("globalblocks", [])
    )


    # ========================================================
    # 5. 判斷 Block
    # ========================================================

    print()

    if len(global_blocks) == 0:

        wikidata_block_ok = True

        print(
            "✅ 目前 IP 未查到 Wikimedia Global Block"
        )


    else:

        wikidata_block_ok = False

        print(
            "❌ 目前 IP 受到 Wikimedia Global Block"
        )

        print()

        for block in global_blocks:

            print(
                f"封鎖範圍："
                f"{block.get('range') or block.get('target')}"
            )

            print(
                f"原因："
                f"{block.get('reason')}"
            )

            print(
                f"到期時間："
                f"{block.get('expiry')}"
            )

            print(
                f"Block ID："
                f"{block.get('id')}"
            )

            print()


    # ========================================================
    # 6. 最終判斷
    # ========================================================

    wikidata_upload_ok = (
        wikidata_login_ok
        and
        wikidata_block_ok
    )


    print("=" * 70)

    if wikidata_upload_ok:

        print(
            "✅ 可以進入 Wikidata 上傳階段"
        )

    else:

        print(
            "❌ 目前不建議執行 Wikidata 上傳"
        )

        if not wikidata_login_ok:

            print(
                "原因：登入或必要權限異常"
            )

        if not wikidata_block_ok:

            print(
                "原因：目前 Colab IP "
                "受到 Wikimedia Global Block"
            )

            print(
                "請重新連線 Colab Runtime "
                "後再次執行 Cell 11.5。"
            )


except Exception as e:

    print()
    print(
        "❌ Cell 11.5 檢查失敗"
    )

    print(
        f"錯誤：{e}"
    )

    wikidata_login_ok = False
    wikidata_block_ok = False
    wikidata_upload_ok = False

======================================================================
Cell 11.5：Wikidata 上傳環境檢查
======================================================================
HTTP Status：200

✅ Wikidata 登入狀態正常

使用者：Kenwu99034
User ID：8352669

必要權限：
✅ read
✅ edit
✅ createpage

----------------------------------------------------------------------
正在檢查目前 Colab 對外 IP...
目前 IP：136.113.13.25

✅ 目前 IP 未查到 Wikimedia Global Block
======================================================================
✅ 可以進入 Wikidata 上傳階段

In [ ]:
# ============================================================
# Cell 11：Wikidata 批次上傳（Wikidata API 上傳 Button 版）
# 取得 CSRF token，使用 OAuth session 呼叫 Wikibase API 建立 Item；成功取得新 QID，失敗則記錄 API error
# api_payloads → 逐筆建立 Wikidata Item
# 注意：
# 按下按鈕後會真的建立全部 api_payloads
# ============================================================

import json
import time
import ipywidgets as widgets
from IPython.display import display, clear_output


# ============================================================
# 1. 基本設定
# ============================================================

API_URL = "https://www.wikidata.org/w/api.php"

HEADERS = {
    "User-Agent": (
        "NPM-Wikidata-Upload-Tool/0.1 "
        "(Wikidata user: Kenwu99034)"
    )
}

# 每筆之間等待秒數
UPLOAD_DELAY = 2


# ============================================================
# 2. 基本檢查
# ============================================================

if len(api_payloads) == 0:

    raise ValueError(
        "沒有可以上傳的 api_payloads。"
    )


# ============================================================
# 3. 初始化本次批次結果
# ============================================================

batch_upload_results = []


# ============================================================
# 4. UI
# ============================================================

info_output = widgets.Output()

upload_output = widgets.Output()


upload_button = widgets.Button(
    description="🚀 確認批次建立",
    button_style="danger",
    tooltip="按下後會真的建立全部 Wikidata Items",
    layout=widgets.Layout(
        width="220px",
        height="42px"
    )
)


# ============================================================
# 5. 顯示批次資訊
# ============================================================

with info_output:

    print("=" * 70)
    print("Cell 11：Wikidata 批次上傳")
    print("=" * 70)

    print()

    print(
        f"準備上傳：{len(api_payloads)} 筆"
    )

    print()

    if wikidata_login_ok:

        print(
            "✅ Wikidata 登入狀態正常"
        )

    else:

        print(
            "❌ Wikidata 尚未登入"
        )

    print()

    print(
        "目前模式：批次建立"
    )

    print(
        f"每筆間隔：{UPLOAD_DELAY} 秒"
    )

    print()

    print(
        "⚠️ 按下紅色按鈕後，"
        "會逐筆建立全部 api_payloads。"
    )


display(info_output)

display(upload_button)

display(upload_output)


# ============================================================
# 6. 取得 CSRF Token
# ============================================================

def get_csrf_token():

    token_response = session.get(

        API_URL,

        params={
            "action": "query",
            "meta": "tokens",
            "type": "csrf",
            "format": "json"
        },

        headers=HEADERS,

        timeout=30
    )

    token_response.raise_for_status()

    token_data = token_response.json()

    return (
        token_data
        ["query"]
        ["tokens"]
        ["csrftoken"]
    )


# ============================================================
# 7. 單筆建立 Function
# ============================================================

def create_wikidata_item(
    upload_item,
    csrf_token
):

    payload_data = upload_item["data"]

    label = upload_item.get(
        "label",
        ""
    )

    row_number = upload_item.get(
        "row_number"
    )


    params = {

        "action":
            "wbeditentity",

        "new":
            "item",

        "data":
            json.dumps(
                payload_data,
                ensure_ascii=False
            ),

        "token":
            csrf_token,

        "format":
            "json",

        "maxlag":
            5,

        "assert":
            "user",

        "summary":
            (
                "Creating National Palace Museum "
                "collection item from official "
                "digital archive data"
            )
    }


    try:

        response = session.post(

            API_URL,

            data=params,

            headers=HEADERS,

            timeout=60
        )


        response.raise_for_status()

        result = response.json()


    except Exception as e:

        return {

            "success": False,

            "qid": None,

            "label": label,

            "row_number": row_number,

            "error_code":
                "REQUEST_ERROR",

            "error_message":
                str(e),

            "response":
                None
        }


    # ========================================================
    # API Error
    # ========================================================

    if "error" in result:

        error = result.get(
            "error",
            {}
        )


        return {

            "success": False,

            "qid": None,

            "label": label,

            "row_number": row_number,

            "error_code":
                error.get("code"),

            "error_message":
                (
                    error.get("info")
                    or str(error)
                ),

            "response":
                result
        }


    # ========================================================
    # Success
    # ========================================================

    if "entity" in result:

        new_qid = (
            result["entity"]
            .get("id")
        )


        return {

            "success": True,

            "qid": new_qid,

            "label": label,

            "row_number": row_number,

            "error_code": None,

            "error_message": None,

            "response":
                result
        }


    # ========================================================
    # Unexpected
    # ========================================================

    return {

        "success": False,

        "qid": None,

        "label": label,

        "row_number": row_number,

        "error_code":
            "UNEXPECTED_RESPONSE",

        "error_message":
            "API 回傳中沒有 entity 或 error",

        "response":
            result
    }


# ============================================================
# 8. Batch Upload
# ============================================================

def upload_all_items(button):

    global batch_upload_results
    global last_upload_result

    # --------------------------------------------------------
    # 防止連點
    # --------------------------------------------------------

    upload_button.disabled = True


    with upload_output:

        clear_output()

        print("=" * 70)
        print("Wikidata 批次上傳程序")
        print("=" * 70)


        # ====================================================
        # A. 上傳環境檢查
        # ====================================================

        if not wikidata_upload_ok:

            print()
            print(
                "❌ 目前 Wikidata 上傳環境不允許寫入"
            )

            if not wikidata_login_ok:

                print(
                    "原因：登入或必要權限異常"
                )

            if not wikidata_block_ok:

                print(
                    "原因：目前 Colab IP "
                    "受到 Wikimedia Global Block"
                )

            print()
            print(
                "⛔ 已取消本次批次上傳"
            )

            upload_button.disabled = False

            return


        # ====================================================
        # 通過檢查
        # ====================================================

        print()
        print(
            "✅ Wikidata 上傳環境確認完成"
        )
        # ====================================================
        # B. 取得 Token
        # ====================================================

        try:

            print()
            print(
                "正在取得 CSRF token..."
            )

            csrf_token = (
                get_csrf_token()
            )

            print(
                "✅ CSRF token 取得成功"
            )


        except Exception as e:

            print()
            print(
                "❌ CSRF token 取得失敗"
            )

            print(
                f"錯誤：{e}"
            )

            upload_button.disabled = False

            return


        # ====================================================
        # C. 開始 Batch
        # ====================================================

        batch_upload_results = []

        total = len(
            api_payloads
        )


        print()
        print(
            f"開始批次建立，共 {total} 筆"
        )

        print(
            "-" * 70
        )


        for index, upload_item in enumerate(
            api_payloads,
            1
        ):

            label = upload_item.get(
                "label",
                ""
            )


            print()
            print(
                f"[{index}/{total}] "
                f"{label}"
            )


            result = create_wikidata_item(
                upload_item,
                csrf_token
            )


            # ------------------------------------------------
            # 立即記錄
            # ------------------------------------------------

            batch_upload_results.append(
                result
            )


            # ------------------------------------------------
            # 同時更新 last_upload_result
            # 方便 Cell 12 相容
            # ------------------------------------------------

            last_upload_result = (
                result
            )


            # ------------------------------------------------
            # Success
            # ------------------------------------------------

            if result["success"]:

                print(
                    f"    ✅ 成功 "
                    f"→ {result['qid']}"
                )


            # ------------------------------------------------
            # Failed
            # ------------------------------------------------

            else:

                print(
                    f"    ❌ 失敗"
                )

                print(
                    f"       code: "
                    f"{result['error_code']}"
                )

                print(
                    f"       message: "
                    f"{result['error_message']}"
                )

                print("\n       完整 API Response：")

                print(
                    json.dumps(
                        result.get("response"),
                        ensure_ascii=False,
                        indent=2
                    )
                )
            # ------------------------------------------------
            # 最後一筆不用 sleep
            # ------------------------------------------------

            if index < total:

                time.sleep(
                    UPLOAD_DELAY
                )


        # ====================================================
        # D. 統計
        # ====================================================

        success_count = sum(
            1
            for result in batch_upload_results
            if result["success"]
        )

        failed_count = (
            total - success_count
        )


        print()
        print("=" * 70)
        print("批次上傳完成")
        print("=" * 70)

        print(
            f"✅ 成功：{success_count}"
        )

        print(
            f"❌ 失敗：{failed_count}"
        )


        if failed_count == 0:

            print()
            print(
                "🔒 全部資料已完成，"
                "上傳按鈕保持鎖定。"
            )


        else:

            print()
            print(
                "⚠️ 有部分資料失敗。"
            )

            print(
                "請先查看錯誤紀錄，"
                "不要直接重新執行整批上傳。"
            )


        # 這裡刻意不重新 enable
        # 避免成功的項目再次被重複建立


# ============================================================
# 9. 綁定 Button
# ============================================================

upload_button.on_click(
    upload_all_items
)

Output()

Button(button_style='danger', description='🚀 確認批次建立', layout=Layout(height='42px', width='220px'), style=Butto…

Output()

In [ ]:
# ============================================================
# Cell 12：Wikidata 批次上傳結果整理(Batch Result / Log)
# 整理批次執行結果，例如成功、失敗、QID、錯誤原因、原始資料索引等
# batch_upload_results
#        ↓
# upload_log
# 注意：
# 此 Cell 不會修改 Wikidata
# ============================================================

import pandas as pd
from IPython.display import display


# ============================================================
# 1. 標題
# ============================================================

print("=" * 70)
print("Cell 12：Wikidata 批次上傳結果整理")
print("=" * 70)


# ============================================================
# 2. 檢查是否有批次結果
# ============================================================

if (
    "batch_upload_results" not in globals()
    or len(batch_upload_results) == 0
):

    print()
    print("⚠️ 尚無批次上傳結果。")
    print("請先完成 Cell 11 批次上傳。")


else:

    # ========================================================
    # 3. 建立 Upload Log
    # ========================================================

    upload_log = []


    for result in batch_upload_results:

        success = result.get(
            "success",
            False
        )

        qid = result.get(
            "qid"
        )

        label = result.get(
            "label",
            ""
        )

        row_number = result.get(
            "row_number"
        )

        error_code = result.get(
            "error_code"
        )

        error_message = result.get(
            "error_message"
        )


        # ----------------------------------------------------
        # 成功
        # ----------------------------------------------------

        if success:

            status = "SUCCESS"

            wikidata_url = (
                f"https://www.wikidata.org/wiki/{qid}"
            )


        # ----------------------------------------------------
        # 失敗
        # ----------------------------------------------------

        else:

            status = "FAILED"

            wikidata_url = None


        upload_log.append({

            "row_number":
                row_number,

            "label":
                label,

            "status":
                status,

            "qid":
                qid,

            "wikidata_url":
                wikidata_url,

            "error_code":
                error_code,

            "error_message":
                error_message
        })


    # ========================================================
    # 4. DataFrame
    # ========================================================

    upload_log_df = pd.DataFrame(
        upload_log
    )


    # ========================================================
    # 5. 統計
    # ========================================================

    total_count = len(
        upload_log_df
    )


    success_count = (
        upload_log_df[
            upload_log_df["status"]
            == "SUCCESS"
        ].shape[0]
    )


    failed_count = (
        upload_log_df[
            upload_log_df["status"]
            == "FAILED"
        ].shape[0]
    )


    print()
    print(
        f"總上傳資料：{total_count}"
    )

    print(
        f"✅ 成功：{success_count}"
    )

    print(
        f"❌ 失敗：{failed_count}"
    )


    # ========================================================
    # 6. 顯示完整 Log
    # ========================================================

    print()
    print("=" * 70)
    print("Upload Log")
    print("=" * 70)

    display(
        upload_log_df
    )


    # ========================================================
    # 7. 顯示成功資料
    # ========================================================

    success_log_df = (
        upload_log_df[
            upload_log_df["status"]
            == "SUCCESS"
        ]
        .copy()
    )


    if len(success_log_df) > 0:

        print()
        print("=" * 70)
        print("✅ 成功建立的 Wikidata Items")
        print("=" * 70)

        display(
            success_log_df[
                [
                    "row_number",
                    "label",
                    "qid",
                    "wikidata_url"
                ]
            ]
        )


    # ========================================================
    # 8. 顯示失敗資料
    # ========================================================

    failed_log_df = (
        upload_log_df[
            upload_log_df["status"]
            == "FAILED"
        ]
        .copy()
    )


    if len(failed_log_df) > 0:

        print()
        print("=" * 70)
        print("❌ 上傳失敗資料")
        print("=" * 70)

        display(
            failed_log_df[
                [
                    "row_number",
                    "label",
                    "error_code",
                    "error_message"
                ]
            ]
        )


    # ========================================================
    # 9. 建立成功 QID Mapping
    #
    # Cell 13 可以直接使用
    # ========================================================

    uploaded_qid_map = {}


    for item in upload_log:

        if (
            item["status"] == "SUCCESS"
            and
            item["qid"]
        ):

            uploaded_qid_map[
                item["row_number"]
            ] = item["qid"]


    # ========================================================
    # 10. 建立 Failed Row Number
    #
    # Cell 13 可以直接使用
    # ========================================================

    failed_row_numbers = set(
        failed_log_df[
            "row_number"
        ].tolist()
    )


    # ========================================================
    # 11. 完成
    # ========================================================

    print()
    print("=" * 70)
    print("Cell 12：結果整理完成")
    print("=" * 70)

    print()

    print(
        f"已記錄 QID："
        f"{len(uploaded_qid_map)} 筆"
    )

    print(
        f"需要後續處理："
        f"{len(failed_row_numbers)} 筆"
    )

    print()

    print(
        "✅ upload_log 已建立"
    )

    print(
        "✅ upload_log_df 已建立"
    )

    print(
        "✅ uploaded_qid_map 已建立"
    )

    print(
        "✅ failed_row_numbers 已建立"
    )

    print(
        "✅ 此 Cell 沒有執行任何 Wikidata 寫入操作"
    )

======================================================================
Cell 12：Wikidata 批次上傳結果整理
======================================================================

總上傳資料：1
✅ 成功：1
❌ 失敗：0

======================================================================
Upload Log
======================================================================

,row_number,label,status,qid,wikidata_url,error_code,error_message
0,1,乃孫作祖己鼎,SUCCESS,Q141031307,https://www.wikidata.org/wiki/Q141031307,None,None

======================================================================
✅ 成功建立的 Wikidata Items
======================================================================

   row_number   label         qid                              wikidata_url
0           1  乃孫作祖己鼎  Q141031307  https://www.wikidata.org/wiki/Q141031307

======================================================================
Cell 12：結果整理完成
======================================================================

已記錄 QID：1 筆
需要後續處理：0 筆

✅ upload_log 已建立
✅ upload_log_df 已建立
✅ uploaded_qid_map 已建立
✅ failed_row_numbers 已建立
✅ 此 Cell 沒有執行任何 Wikidata 寫入操作

In [ ]:
# ============================================================
# Cell 13：上傳結果回寫與匯出(結果回寫／匯出)
# 把新建立的 QID、上傳狀態、錯誤資訊等回寫到結果資料，最後輸出成 Excel／CSV
# Cell 12
# upload_log / uploaded_qid_map / failed_row_numbers
#        ↓
# 回寫 Wikidata QID
#        ↓
# retry_payloads
#        ↓
# Excel / CSV
#
# 注意：
# 此 Cell 不會修改 Wikidata
# ============================================================

import pandas as pd
from datetime import datetime
from IPython.display import display


# ============================================================
# 1. 基本檢查
# ============================================================

print("=" * 70)
print("Cell 13：Wikidata 上傳結果回寫與匯出")
print("=" * 70)


required_variables = [
    "upload_log",
    "uploaded_qid_map",
    "failed_row_numbers"
]


missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]


if missing_variables:

    print()
    print(
        "❌ 缺少 Cell 12 產生的變數："
    )

    for name in missing_variables:

        print(
            f"  - {name}"
        )

    print()
    print(
        "請先執行 Cell 12。"
    )


else:

    # ========================================================
    # 2. 複製原始處理資料
    # ========================================================

    result_df = wikidata_df.copy()


    # ========================================================
    # 3. 建立 Wikidata_QID
    # ========================================================

    result_df[
        "Wikidata_QID"
    ] = None


    for index in result_df.index:

        # 前面 row_number = index + 1
        row_number = index + 1


        if row_number in uploaded_qid_map:

            result_df.at[
                index,
                "Wikidata_QID"
            ] = (
                uploaded_qid_map[
                    row_number
                ]
            )


    # ========================================================
    # 4. 建立 Wikidata_URL
    # ========================================================

    result_df[
        "Wikidata_URL"
    ] = result_df[
        "Wikidata_QID"
    ].apply(

        lambda qid:

        (
            f"https://www.wikidata.org/wiki/{qid}"
        )

        if pd.notna(qid)
        and str(qid).strip() != ""

        else None
    )


    # ========================================================
    # 5. 建立 Upload_Status
    # ========================================================

    status_map = {
        item["row_number"]:
            item["status"]

        for item in upload_log
    }


    result_df[
        "Upload_Status"
    ] = None


    for index in result_df.index:

        row_number = index + 1

        if row_number in status_map:

            result_df.at[
                index,
                "Upload_Status"
            ] = status_map[
                row_number
            ]


    # ========================================================
    # 6. 建立 Retry Payload
    # ========================================================

    retry_payloads = []


    for item in api_payloads:

        row_number = item.get(
            "row_number"
        )

        if row_number in failed_row_numbers:

            retry_payloads.append(
                item
            )


    # ========================================================
    # 7. 建立成功 / 失敗 DataFrame
    # ========================================================

    upload_log_export_df = (
        pd.DataFrame(
            upload_log
        )
    )


    success_export_df = (
        upload_log_export_df[
            upload_log_export_df[
                "status"
            ] == "SUCCESS"
        ]
        .copy()
    )


    failed_export_df = (
        upload_log_export_df[
            upload_log_export_df[
                "status"
            ] == "FAILED"
        ]
        .copy()
    )


    # ========================================================
    # 8. 統計
    # ========================================================

    total_count = len(
        upload_log_export_df
    )

    success_count = len(
        success_export_df
    )

    failed_count = len(
        failed_export_df
    )


    print()
    print(
        f"本次上傳結果：{total_count} 筆"
    )

    print(
        f"✅ 成功：{success_count}"
    )

    print(
        f"❌ 失敗：{failed_count}"
    )

    print(
        f"🔁 可重試：{len(retry_payloads)}"
    )


    # ========================================================
    # 9. 顯示回寫結果
    # ========================================================

    print()
    print("=" * 70)
    print("QID 回寫結果")
    print("=" * 70)


    preview_columns = []


    # 有哪些欄位就顯示哪些
    for column in [
        "品名",
        "文物統一編號",
        "Wikidata_QID",
        "Wikidata_URL",
        "Upload_Status"
    ]:

        if column in result_df.columns:

            preview_columns.append(
                column
            )


    display(
        result_df[
            preview_columns
        ]
    )


    # ========================================================
    # 10. 建立時間戳記
    # ========================================================

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )


    excel_filename = (
        f"npm_wikidata_upload_"
        f"{timestamp}.xlsx"
    )


    csv_filename = (
        f"npm_wikidata_upload_log_"
        f"{timestamp}.csv"
    )


    # ========================================================
    # 11. 匯出 Excel
    # ========================================================

    with pd.ExcelWriter(
        excel_filename,
        engine="openpyxl"
    ) as writer:

        # ----------------------------------------------
        # 原始資料 + QID + 狀態
        # ----------------------------------------------

        result_df.to_excel(
            writer,
            sheet_name="Upload_Result",
            index=False
        )


        # ----------------------------------------------
        # 全部 Log
        # ----------------------------------------------

        upload_log_export_df.to_excel(
            writer,
            sheet_name="Upload_Log",
            index=False
        )


        # ----------------------------------------------
        # 成功
        # ----------------------------------------------

        success_export_df.to_excel(
            writer,
            sheet_name="Success",
            index=False
        )


        # ----------------------------------------------
        # 失敗
        # ----------------------------------------------

        failed_export_df.to_excel(
            writer,
            sheet_name="Failed",
            index=False
        )


    # ========================================================
    # 12. 匯出 CSV Log
    # ========================================================

    upload_log_export_df.to_csv(
        csv_filename,
        index=False,
        encoding="utf-8-sig"
    )


    # ========================================================
    # 13. 完成訊息
    # ========================================================

    print()
    print("=" * 70)
    print("Cell 13：完成")
    print("=" * 70)

    print()

    print(
        f"Excel：{excel_filename}"
    )

    print(
        f"CSV：{csv_filename}"
    )

    print()

    print(
        f"✅ 已回寫 QID："
        f"{len(uploaded_qid_map)} 筆"
    )

    print(
        f"🔁 retry_payloads："
        f"{len(retry_payloads)} 筆"
    )

    print()

    print(
        "✅ 此 Cell 沒有執行任何 Wikidata 寫入操作"
    )

======================================================================
Cell 13：Wikidata 上傳結果回寫與匯出
======================================================================

本次上傳結果：1 筆
✅ 成功：1
❌ 失敗：0
🔁 可重試：0

======================================================================
QID 回寫結果
======================================================================

,品名,文物統一編號,Wikidata_QID,Wikidata_URL,Upload_Status
0,乃孫作祖己鼎,故銅002343N000000000,Q141031307,https://www.wikidata.org/wiki/Q141031307,SUCCESS

======================================================================
Cell 13：完成
======================================================================

Excel：npm_wikidata_upload_20260813_041928.xlsx
CSV：npm_wikidata_upload_log_20260813_041928.csv

✅ 已回寫 QID：1 筆
🔁 retry_payloads：0 筆

✅ 此 Cell 沒有執行任何 Wikidata 寫入操作

In [ ]:
# ============================================================
# OAuth 2 Scope 診斷(診斷程式)
# 不會修改 Wikidata
# ============================================================

SCOPES_URL = (
    "https://www.wikidata.org/w/rest.php/"
    "oauth2/resource/scopes"
)

response = session.get(
    SCOPES_URL,
    timeout=30
)

print("HTTP Status:", response.status_code)

try:
    print(response.json())
except Exception:
    print(response.text)

HTTP Status: 200
{'scopes': ['basic', 'editpage', 'createeditmovepage']}

In [ ]:
# ============================================================
# Wikidata 寫入權限詳細診斷
# 不會建立或修改任何 Item
# ============================================================

API_URL = "https://www.wikidata.org/w/api.php"

print("=" * 70)
print("Wikidata 寫入權限詳細診斷")
print("=" * 70)

response = session.get(
    API_URL,
    params={
        "action": "query",
        "meta": "userinfo",
        "uiprop": "rights|groups|implicitgroups",
        "format": "json"
    },
    timeout=30
)

print("HTTP Status:", response.status_code)

data = response.json()

userinfo = (
    data
    .get("query", {})
    .get("userinfo", {})
)

rights = userinfo.get("rights", [])
groups = userinfo.get("groups", [])
implicitgroups = userinfo.get("implicitgroups", [])

print()
print("使用者：", userinfo.get("name"))
print()

print("Groups：")
print(groups)

print()

print("Implicit Groups：")
print(implicitgroups)

print()

print("重要權限檢查：")

required_rights = [
    "read",
    "edit",
    "createpage"
]

for right in required_rights:

    if right in rights:
        print(f"✅ {right}")
    else:
        print(f"❌ {right}")

print()
print("完整 Rights：")
print(rights)

======================================================================
Wikidata 寫入權限詳細診斷
======================================================================
HTTP Status: 200

使用者： Kenwu99034

Groups：
['*', 'user', 'autoconfirmed']

Implicit Groups：
['*', 'user', 'autoconfirmed']

重要權限檢查：
✅ read
✅ edit
✅ createpage

完整 Rights：
['autocreateaccount', 'read', 'edit', 'createpage', 'createtalk', 'translate', 'abusefilter-view', 'abusefilter-log', 'unfuzzy', 'translate-empty-category', 'flow-hide', 'flow-edit-title', 'item-term', 'property-term', 'item-merge', 'item-redirect', 'wbqc-check-constraints', 'move-rootuserpages', 'move-categorypages', 'minoredit', 'applychangetags', 'wbqc-check-constraints-uncached', 'autopatrol', 'move', 'createwithcontentmodel', 'autoconfirmed', 'editsemiprotected', 'skipcaptcha', 'abusefilter-log-detail', 'flow-edit-post']

In [ ]:
# ============================================================
# 測試 A：assert=user (診斷程式)
# 不會寫入 Wikidata
# ============================================================

API_URL = "https://www.wikidata.org/w/api.php"

response = session.get(
    API_URL,
    params={
        "action": "query",
        "meta": "userinfo",
        "uiprop": "rights",
        "assert": "user",
        "format": "json"
    },
    timeout=30
)

print("HTTP Status:", response.status_code)
print(response.json())

HTTP Status: 200
{'batchcomplete': '', 'query': {'userinfo': {'id': 8352669, 'name': 'Kenwu99034', 'rights': ['autocreateaccount', 'read', 'edit', 'createpage', 'createtalk', 'translate', 'abusefilter-view', 'abusefilter-log', 'unfuzzy', 'translate-empty-category', 'flow-hide', 'flow-edit-title', 'item-term', 'property-term', 'item-merge', 'item-redirect', 'wbqc-check-constraints', 'move-rootuserpages', 'move-categorypages', 'minoredit', 'applychangetags', 'wbqc-check-constraints-uncached', 'autopatrol', 'move', 'createwithcontentmodel', 'autoconfirmed', 'editsemiprotected', 'skipcaptcha', 'abusefilter-log-detail', 'flow-edit-post']}}}

In [ ]:
# ============================================================
# 測試 B：Session Authentication 診斷 (診斷程式)
# 不顯示 Token
# 不會寫入 Wikidata
# ============================================================

print("Session type:")
print(type(session))

print("\nSession auth type:")
print(
    type(session.auth)
    if getattr(session, "auth", None) is not None
    else "None"
)

print("\nAuthorization header exists:")
print(
    "Authorization" in session.headers
)

print("\nCookie 數量:")
print(
    len(session.cookies)
)

Session type:
<class 'requests.sessions.Session'>

Session auth type:
None

Authorization header exists:
True

Cookie 數量:
6

In [ ]:
# ============================================================
# wbeditentity 完整錯誤診斷 (診斷程式)
# 注意：這會真正嘗試建立第一筆 Item
# ============================================================

import json

API_URL = "https://www.wikidata.org/w/api.php"

upload_item = api_payloads[0]
payload_data = upload_item["data"]

# 取得 CSRF
token_response = session.get(
    API_URL,
    params={
        "action": "query",
        "meta": "tokens",
        "type": "csrf",
        "format": "json"
    },
    timeout=30
)

csrf_token = (
    token_response.json()
    ["query"]
    ["tokens"]
    ["csrftoken"]
)

params = {
    "action": "wbeditentity",
    "new": "item",
    "data": json.dumps(
        payload_data,
        ensure_ascii=False
    ),
    "token": csrf_token,
    "format": "json",
    "assert": "user",
    "maxlag": 5
}

response = session.post(
    API_URL,
    data=params,
    timeout=60
)

print("HTTP Status:", response.status_code)

result = response.json()

print(
    json.dumps(
        result,
        ensure_ascii=False,
        indent=2
    )
)

HTTP Status: 200
{
  "error": {
    "code": "permissiondenied",
    "info": "You do not have the permissions needed to carry out this action.",
    "messages": [
      {
        "name": "wikibase-api-permissiondenied",
        "parameters": [],
        "html": {
          "*": "您無權操作"
        }
      },
      {
        "name": "globalblocking-blockedtext-range",
        "parameters": [
          "[[User:JJMC89|‪JJMC89‬]]",
          "[[m:Special:MyLanguage/NOP|Open proxy/Webhost]]: See the [[m:WM:OP/H|help page]] if you are affected <!-- Google Cloud -->",
          "34.132.151.224",
          "‪JJMC89‬",
          3249896,
          "2027年7月3日 (六) 00:52",
          "34.132.0.0/16",
          "2024年7月3日 (三) 00:52",
          "",
          ""
        ],
        "html": {
          "*": "<p><b>您的IP位址處於<a href=\"https://meta.wikimedia.org/wiki/Special:MyLanguage/Global_blocks\" class=\"extiw\" title=\"m:Special:MyLanguage/Global blocks\">所有維基媒體基金會wiki上被封鎖</a>的區段範圍內。</b>\n</p><p>封鎖由<a href=\"/wiki/User:JJMC89\" title=\"User:JJMC89\">‪JJMC89‬</a>做出。\n給出的原因是<i><a href=\"https://meta.wikimedia.org/wiki/Special:MyLanguage/NOP\" class=\"extiw\" title=\"m:Special:MyLanguage/NOP\">Open proxy/Webhost</a>: See the <a href=\"https://meta.wikimedia.org/wiki/WM:OP/H\" class=\"extiw\" title=\"m:WM:OP/H\">help page</a> if you are affected </i>。\n</p>\n<ul><li>封鎖開始時間：2024年7月3日 (三) 00:52</li>\n<li>封鎖結束時間：2027年7月3日 (六) 00:52</li></ul>\n<p>您目前的IP位址是34.132.151.224。\n被封鎖的位址段為34.132.0.0/16。\n</p><p>請您在詢問時附註以上詳細資料。\n如果您認為自己被封鎖是場錯誤，可以在[[m:Special:MyLanguage/Stewards/Wizard\n|監管員封鎖精靈]]中檢視更多資訊和說明。\n</p>"
        }
      }
    ],
    "*": "See https://www.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."
  },
  "servedby": "mw-api-ext.eqiad.main-98459d7f8-l4ckr"
}